/**
 * Module-owned operation descriptor declarations.
 *
 * An operation descriptor is the single authority for a module-owned
 * transport operation (method, path, scope, capability, request mapping,
 * response decoder, and client namespace).
 *
 * Routine operations are generated by the transport bindings pipeline,
 * making routine consistency true by construction. Classified exceptions
 * require authored adapters that explicitly name their exceptional
 * semantic or security responsibility (e.g. interactive authentication,
 * binary streaming, error status transformation).
 */

export type OperationClassification = "routine" | "exception";

export type OperationParameterType =
  | "path"
  | "query"
  | "queryOptions"
  | "body"
  | "bodySpread"
  | "bodyFilter"
  | "bodyDirect"
  | "scopeQuery";

export type OperationParameterMapping = {
  readonly name: string;
  readonly type: OperationParameterType;
  readonly optional?: boolean;
};

export type ModuleOperationDef = {
  readonly id: string;
  readonly namespace: string;
  readonly clientMethod: string;
  readonly method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  readonly path: string;
  readonly capabilityScope?: "read" | "write";
  readonly scope?: "scope" | "daemon" | "optional";
  readonly classification: OperationClassification;
  readonly exceptionReason?: string;
  readonly parameters?: readonly OperationParameterMapping[];
  readonly responseType?: string;
  readonly responseDecoder?: string;
};

export function defineModuleOperation(
  def: ModuleOperationDef,
): ModuleOperationDef {
  return Object.freeze({ ...def });
}
