import { StyleSheet } from 'react-native';

export const navigationStyles = StyleSheet.create({
  fullScreen: { flex: 1, backgroundColor: '#f2f2f7' },
  closeConnection: {
    zIndex: 1,
    minHeight: 48,
    alignSelf: 'flex-end',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  closeConnectionLabel: { color: '#0a67c7', fontSize: 15, fontWeight: '700' },
  tabGlyph: { fontSize: 16, fontWeight: '800' },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    backgroundColor: '#f2f2f7',
    padding: 28,
  },
  messageTitle: {
    color: '#1c1c1e',
    fontSize: 21,
    fontWeight: '800',
    textAlign: 'center',
  },
  messageDetail: {
    color: '#6c6c70',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  primaryButton: {
    minHeight: 48,
    minWidth: 160,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: '#0a67c7',
    paddingHorizontal: 16,
  },
  primaryButtonLabel: { color: '#ffffff', fontSize: 15, fontWeight: '700' },
  secondaryButton: {
    minHeight: 48,
    minWidth: 160,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#c7c7cc',
    borderRadius: 9,
    paddingHorizontal: 16,
  },
  secondaryButtonLabel: { color: '#1c1c1e', fontSize: 15, fontWeight: '600' },
  routeScreen: { flex: 1, backgroundColor: '#f2f2f7' },
  routeContent: { gap: 16, padding: 16, paddingBottom: 40 },
  routeHeader: {
    gap: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: '#c7c7cc',
    paddingBottom: 14,
  },
  routeEyebrow: {
    color: '#6c6c70',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  routePath: { color: '#1c1c1e', fontSize: 18, fontWeight: '800' },
  routeDocument: {
    color: '#1c1c1e',
    fontFamily: 'monospace',
    fontSize: 13,
    lineHeight: 19,
  },
});
