import type { AutonomyReportData } from "./aggregate.js";
import { PROCESS_DISCIPLINE_RUBRIC_VERSION } from "./process-discipline-report.js";

export const baseReportWindow = {
  windowStartedAt: "2026-04-22T12:00:00.000Z",
  windowEndedAt: "2026-04-29T12:00:00.000Z",
  windowDays: 7,
};

export const emptyAutonomyReportData: AutonomyReportData = {
  ...baseReportWindow,
  supervisionLoad: {
    generatedAt: baseReportWindow.windowEndedAt,
    status: "normal",
    counts: {
      activeRuns: 0,
      activeTaskClaims: 0,
      pendingMergeTaskClaims: 0,
      blockedClaimRecoveries: 0,
      pendingApprovals: 0,
      pendingOwnerQuestions: 0,
      openDeadLetters: 0,
      attentionItems: 0,
      postCompletionFollowUps: 0,
      reviewEvidenceGaps: 0,
    },
    score: {
      status: "normal",
      score: 0,
      knownScore: 0,
      unknownEvidenceCount: 0,
    },
    thresholds: {
      busyAt: 3,
      overloadedAt: 6,
      weights: {
        activeRuns: 1,
        activeTaskClaims: 1,
        pendingMergeTaskClaims: 2,
        blockedClaimRecoveries: 2,
        pendingApprovals: 2,
        pendingOwnerQuestions: 2,
        openDeadLetters: 2,
        attentionItems: 1,
        postCompletionFollowUps: 1,
        reviewEvidenceGaps: 1,
      },
    },
    evidence: [],
    workstreams: [],
    topReferences: [],
  },
  openQueue: {
    total: 0,
    byPriority: [],
    byArea: [],
    byState: [],
    byTaskClass: [],
    waitingOnTasks: [],
  },
  doneInWindow: {
    total: 0,
    byPriority: [],
    byArea: [],
    byState: [],
    byTaskClass: [],
    waitingOnTasks: [],
  },
  explorer: {
    totalRuns: 0,
    totalTaskAdditions: 0,
    unresolvedTaskAdditions: 0,
    byClassification: [
      { classification: "strategic", tasks: 0 },
      { classification: "fan-out", tasks: 0 },
      { classification: "other", tasks: 0 },
    ],
    taskAdditions: [],
  },
  builder: {
    totalCommittedRuns: 0,
    unresolvedClosures: 0,
    byArea: [],
    byPriority: [],
    byClassification: [],
    closures: [],
  },
  decisionAttribution: {
    totalRuns: 0,
    byPlanning: [],
    byExecution: [],
    byWorkMode: [],
    hardSuccessSignals: [],
    troubleSignals: [],
    warnings: [],
    records: [],
  },
  diffSummaryConsistency: {
    totalBuilderRuns: 0,
    recordedRuns: 0,
    runsWithMismatches: 0,
    totalMismatches: 0,
    byCategory: [],
    missingData: [],
    examples: [],
  },
  reviewScrutiny: {
    totalReviews: 0,
    approvalLikeDecisions: 0,
    thinAcceptances: 0,
    absentMetricCount: 0,
    unsupportedArtifacts: 0,
    bySurface: [
      { surface: "critic", reviews: 0, approvalLikeDecisions: 0, thinAcceptances: 0, absentMetricCount: 0, unsupportedArtifacts: 0 },
      { surface: "progress-reviewer", reviews: 0, approvalLikeDecisions: 0, thinAcceptances: 0, absentMetricCount: 0, unsupportedArtifacts: 0 },
      { surface: "pr-reviewer", reviews: 0, approvalLikeDecisions: 0, thinAcceptances: 0, absentMetricCount: 0, unsupportedArtifacts: 0 },
      { surface: "semantic-gate", reviews: 0, approvalLikeDecisions: 0, thinAcceptances: 0, absentMetricCount: 0, unsupportedArtifacts: 0 },
    ],
    thinAcceptanceRefs: [],
    absentMetricRefs: [],
    records: [],
    unsupported: [],
  },
  reviewScrutinyEscalation: {
    activePatterns: [],
    cooldownPatterns: [],
    belowThresholdPatterns: [],
  },
  shadowSemanticReviews: {
    totalArtifacts: 0,
    reviewed: 0,
    catches: 0,
    falsePositiveAnnotations: 0,
    skippedTargetResolution: 0,
    malformedArtifacts: 0,
    errorArtifacts: 0,
    totalCostUsd: 0,
    averageDurationMs: null,
    byWorkflow: [],
    records: [],
    unsupported: [],
  },
  trajectoryDiagnostics: { activePatterns: [] },
  processDiscipline: {
    rubricVersion: PROCESS_DISCIPLINE_RUBRIC_VERSION,
    weakSampleThreshold: 3,
    totalRecords: 0,
    records: [],
    groups: [],
  },
  autonomyChangeDecisions: {
    totalDecisions: 0,
    invalidArtifacts: [],
    decisions: [],
  },
  codeHealthDrift: {
    totalBuilderRuns: 0,
    runsWithWarnings: 0,
    unsupportedArtifacts: 0,
    byWarningFamily: [],
    bySurfaceArea: [],
    repeatedSurfaces: [],
    trendBuckets: [
      {
        bucket: "current",
        totalBuilderRuns: 0,
        runsWithWarnings: 0,
        warningRecords: 0,
        cleanupExceptionRuns: 0,
        unsupportedArtifacts: 0,
      },
      {
        bucket: "prior",
        totalBuilderRuns: 0,
        runsWithWarnings: 0,
        warningRecords: 0,
        cleanupExceptionRuns: 0,
        unsupportedArtifacts: 0,
      },
    ],
    records: [],
  },
  ownerInterventions: {
    totalQuestions: 0,
    pending: 0,
    stalePending: 0,
    answered: 0,
    answeredCorrections: 0,
    dismissed: 0,
    timeouts: 0,
    legacyUnknown: 0,
    byStatus: [],
    byOutcome: [],
    byAnswerBehavior: [],
    bySource: [],
    byWorkflow: [],
    byTask: [],
    records: [],
    recurringPatterns: {
      activePatterns: [],
      ignoredPatterns: [],
      belowThresholdPatterns: [],
    },
  },
  postCompletionFollowUps: {
    totalCorrectiveFollowUps: 0,
    linkedCompletedTaskCount: 0,
    byReason: [],
    completedTaskIds: [],
    activeFollowUpTaskIds: [],
    links: [],
    truncatedLinkCount: 0,
  },
  qualityStratification: {
    weakSampleThreshold: 3,
    aggregates: [
      {
        signal: "review-scrutiny",
        current: { sampleCount: 0, numeratorCount: 0, denominatorCount: 0, rate: null },
        prior: { sampleCount: 0, numeratorCount: 0, denominatorCount: 0, rate: null },
        rateDelta: null,
        weakEvidence: false,
      },
      {
        signal: "code-health-drift",
        current: { sampleCount: 0, numeratorCount: 0, denominatorCount: 0, rate: null },
        prior: { sampleCount: 0, numeratorCount: 0, denominatorCount: 0, rate: null },
        rateDelta: null,
        weakEvidence: false,
      },
      {
        signal: "post-completion-follow-up",
        current: { sampleCount: 0, numeratorCount: 0, denominatorCount: 0, rate: null },
        prior: { sampleCount: 0, numeratorCount: 0, denominatorCount: 0, rate: null },
        rateDelta: null,
        weakEvidence: false,
      },
    ],
    slices: [],
    missingDimensions: [],
    compositionShifts: [],
  },
  health: {
    totalSignals: 0,
    totalGroups: 0,
    bySeverity: [],
    byLabel: [],
    byScope: [],
    bySource: [],
    byActionability: [],
    topGroups: [],
  },
  blockers: { totalBlocked: 0, byKind: [] },
  cost: {
    totalCostUsd: 0,
    finishedRuns: 0,
    averagePerFinishedRun: 0,
    byWorkflow: [],
  },
};
