import { StyleSheet } from 'react-native';

export const actionStyles = StyleSheet.create({
  card: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#d1d1d6',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  highlighted: { borderWidth: 2, borderColor: '#0a67c7' },
  expandButton: {
    minHeight: 48,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
  },
  expandLabel: { flex: 1, color: '#1c1c1e', fontSize: 15, fontWeight: '600' },
  chevron: { color: '#8e8e93', fontSize: 25 },
  body: { padding: 14, gap: 12 },
  field: { gap: 6 },
  booleanField: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fieldLabel: { color: '#1c1c1e', fontSize: 14, fontWeight: '600' },
  input: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: '#c7c7cc',
    borderRadius: 9,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#1c1c1e',
    backgroundColor: '#ffffff',
  },
  multiline: { minHeight: 100, textAlignVertical: 'top' },
  options: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  requirements: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  requirement: {
    borderRadius: 10,
    backgroundColor: '#e5e5ea',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  requirementLabel: { color: '#3a3a3c', fontSize: 10, fontWeight: '600' },
  option: {
    minHeight: 48,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#c7c7cc',
    borderRadius: 21,
    paddingHorizontal: 14,
  },
  optionSelected: { borderColor: '#0a67c7', backgroundColor: '#eaf3fc' },
  optionLabel: { color: '#3a3a3c', fontWeight: '500' },
  optionLabelSelected: { color: '#0a67c7' },
  actionRow: { gap: 8 },
  button: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: '#0a67c7',
    paddingHorizontal: 16,
  },
  buttonDisabled: { backgroundColor: '#aeaeb2' },
  dangerButton: { backgroundColor: '#b42318' },
  buttonLabel: { color: '#ffffff', fontSize: 15, fontWeight: '700' },
  secondaryButton: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#c7c7cc',
    paddingHorizontal: 16,
  },
  secondaryLabel: { color: '#1c1c1e', fontSize: 15, fontWeight: '600' },
  operation: { color: '#6c6c70', fontSize: 11 },
  hint: { color: '#6c6c70', fontSize: 12, lineHeight: 17 },
  unavailable: { color: '#995c00', fontSize: 12, lineHeight: 17 },
  confirmation: {
    gap: 10,
    borderWidth: 1,
    borderColor: '#e1a325',
    borderRadius: 10,
    backgroundColor: '#fff8e8',
    padding: 12,
  },
  confirmTitle: { color: '#1c1c1e', fontSize: 15, fontWeight: '700' },
  confirmDetail: { color: '#3a3a3c', fontSize: 13, lineHeight: 19 },
  confirmButtons: { gap: 8 },
  error: { color: '#b42318', fontSize: 13, lineHeight: 19 },
  success: { color: '#237a42', fontSize: 13, lineHeight: 19 },
});
