import { StyleSheet } from 'react-native';

export const nodeStyles = StyleSheet.create({
  section: { gap: 10 },
  sectionTitle: { color: '#1c1c1e', fontSize: 16, fontWeight: '700' },
  body: { color: '#3a3a3c', fontSize: 14, lineHeight: 21 },
  progressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  progressTrack: {
    height: 9,
    borderRadius: 5,
    backgroundColor: '#e5e5ea',
    overflow: 'hidden',
  },
  progressFill: { height: '100%', borderRadius: 5, backgroundColor: '#0a67c7' },
  streamMeta: { color: '#6c6c70', fontSize: 11 },
  logs: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#d1d1d6',
    borderRadius: 10,
    backgroundColor: '#f7f7f8',
    overflow: 'hidden',
  },
  logEntry: {
    gap: 3,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e5e5ea',
    padding: 10,
  },
  logMeta: { color: '#6c6c70', fontSize: 10, fontWeight: '600' },
  logMessage: { color: '#1c1c1e', fontFamily: 'monospace', fontSize: 12 },
  actionList: { gap: 10 },
  tabList: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  tab: {
    minHeight: 48,
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
    paddingHorizontal: 12,
  },
  selectedTab: { borderBottomColor: '#0a67c7' },
  tabLabel: { color: '#6c6c70', fontSize: 14, fontWeight: '600' },
  selectedTabLabel: { color: '#0a67c7' },
  tabPanel: { gap: 20 },
  messageCard: {
    gap: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#d1d1d6',
    borderRadius: 12,
    backgroundColor: '#f7f7f8',
    padding: 14,
  },
  errorCard: { borderColor: '#d92d20', backgroundColor: '#fff1f0' },
  errorText: { color: '#b42318' },
  muted: { color: '#6c6c70', fontSize: 13 },
});
