import type { OwnerInterventionPattern } from "./owner-intervention-escalation-types.js";

function formatList(values: readonly string[]): string {
  return values.length > 0 ? values.join(", ") : "(none)";
}

export function buildOwnerInterventionTaskBody(
  pattern: OwnerInterventionPattern,
): string {
  const evidenceLines = pattern.evidence.map((ref) => {
    const refs = [
      ref.refs.question,
      ref.refs.run,
      ref.refs.task,
    ].filter((value): value is string => value !== null);
    const markers = ref.markers.length > 0 ? `; markers: ${ref.markers.join(", ")}` : "";
    return `- ${ref.questionId} ${ref.status} ${ref.outcomeBucket}; refs: ${refs.join(" ") || "(none)"}; source: ${ref.source}${markers}`;
  });
  return [
    "",
    "## Problem",
    "",
    "Recent owner-question records show the same owner-intervention pattern",
    "crossing the escalation threshold. One correction or unanswered prompt can",
    "be normal; this task exists because the repeated pattern points to a local",
    "workflow, task-shaping, prompt, or fallback behavior that should improve.",
    "",
    `Pattern fingerprint: \`${pattern.fingerprint}\``,
    `Evidence fingerprint: \`${pattern.evidenceFingerprint}\``,
    "",
    "## Owner-Intervention Evidence",
    "",
    `- Pattern kind: ${pattern.kind}`,
    `- Grouping dimension: ${pattern.dimension.kind} ${pattern.dimension.value}`,
    `- Questions: ${pattern.questionCount}`,
    `- Distinct runs: ${pattern.distinctRunCount}`,
    `- Outcome buckets: ${pattern.outcomeBuckets.join(", ")}`,
    `- Statuses: ${pattern.statuses.join(", ")}`,
    `- Workflow names: ${formatList(pattern.workflowNames)}`,
    `- Sources: ${formatList(pattern.sources)}`,
    `- Task ids: ${formatList(pattern.taskIds)}`,
    `- Run ids: ${formatList(pattern.runIds)}`,
    `- Owner-question ids: ${formatList(pattern.questionIds)}`,
    `- Window: ${pattern.windowStart} to ${pattern.windowEnd}`,
    `- Active reason: ${pattern.codeActionableReason ?? "code-actionable owner-intervention pattern"}`,
    "",
    ...evidenceLines,
    "",
    "## Desired Outcome",
    "",
    "Repair the local workflow, prompt contract, task-shaping rule, or fallback",
    "path so comparable work no longer needs repeated owner corrections or",
    "stale/expired owner prompts for the same grouped source.",
    "",
    "## Constraints",
    "",
    "- Build on existing owner-question records and owner-intervention report",
    "  aggregation; do not add another intervention ledger or metrics store.",
    "- Keep owner answers sensitive: use ids, statuses, outcome buckets,",
    "  timestamps, workflow/source/task refs, and short sanitized summaries only.",
    "- Do not infer private owner intent from long free-form answers.",
    "- Treat provider outages, missing credentials, and setup-only answers as",
    "  report or blocked-promoter signals unless local handling is the defect.",
    "- Keep spend metrics and owner answer bodies out of autonomy-agent prompts.",
    "",
    "## Product / Safety Link",
    "",
    "This Safety repair supports the Product claim that KOTA's autonomous loop",
    "can be trusted from operator-visible evidence, and the Safety concern that",
    "repeated owner corrections should not stay hidden behind successful runs.",
    "",
    "## Done When",
    "",
    "- Fresh owner-intervention windows no longer trigger this pattern",
    "  fingerprint, or the detector threshold/fingerprint is deliberately",
    "  adjusted with focused tests and evidence.",
    "- Comparable owner-question paths record enough workflow/source/task",
    "  metadata for later review without exposing raw owner answer bodies.",
    "- Operator-facing report or attention output still names future recurring",
    "  owner-intervention patterns and repair task ids without answer bodies,",
    "  prompts, secrets, diffs, spend metrics, or hidden reasoning.",
    "",
    "## Source / Intent",
    "",
    "Auto-created by `owner-intervention-escalator` from sanitized",
    "owner-question records. Repeated owner corrections and stale prompts should",
    "become one bounded repair task instead of remaining only in a report trend.",
    "",
    "## Initiative",
    "",
    "Outcome-aware autonomy governance.",
    "",
    "## Acceptance Evidence",
    "",
    "- Focused test output for the repaired owner-question or workflow path.",
    "- Detector or report fixture showing this pattern no longer crosses the",
    "  escalation gate on fresh evidence.",
    "- Operator-facing report or attention fixture showing future escalations",
    "  include the repair task id without owner answer bodies or spend metrics.",
    "",
    `<!-- owner-intervention-pattern-fingerprint: ${pattern.fingerprint} -->`,
    `<!-- owner-intervention-evidence-fingerprint: ${pattern.evidenceFingerprint} -->`,
    "",
  ].join("\n");
}
