import type { ReviewScrutinyPatternCandidate } from "./review-scrutiny-escalation-types.js";

export function buildReviewScrutinyTaskBody(
  pattern: ReviewScrutinyPatternCandidate,
): string {
  const evidenceLines = pattern.evidence.map((ref) => {
    const target = ref.pr ? `${ref.pr.repo}#${ref.pr.number}` : ref.taskId ?? "(no task)";
    const signals = Object.entries(ref.signals)
      .map(([key, value]) => `${key}=${value}`)
      .join(", ");
    return `- ${ref.runId} ${ref.surface} ${ref.decision} ${target} ${ref.artifactPath}; signals: ${signals || "(none)"}; absent: ${ref.absentMetrics.join(", ") || "(none)"}`;
  });
  return [
    "",
    "## Problem",
    "",
    "Recent review-scrutiny artifacts show the same reviewer surface repeatedly",
    "accepting work with no concrete scrutiny signal. One concise approval can",
    "be valid; this task exists because the grouped pattern crossed the minimum",
    "sample and thin-acceptance ratio thresholds.",
    "",
    `Pattern fingerprint: \`${pattern.fingerprint}\``,
    `Evidence fingerprint: \`${pattern.evidenceFingerprint}\``,
    "",
    "## Review-Scrutiny Evidence",
    "",
    `- Reviewer surface: ${pattern.surface}`,
    `- Workflow/context: ${pattern.workflow} ${pattern.taskArea}/${pattern.taskClass}`,
    `- Thin acceptances: ${pattern.thinAcceptances}/${pattern.approvalLikeDecisions} (${pattern.thinAcceptanceRatio.toFixed(2)})`,
    `- Decisions: ${pattern.decisions.join(", ")}`,
    `- Run ids: ${pattern.runIds.join(", ")}`,
    `- Task ids: ${pattern.taskIds.length > 0 ? pattern.taskIds.join(", ") : "(none)"}`,
    `- Window: ${pattern.windowStart} to ${pattern.windowEnd}`,
    `- Active reason: ${pattern.reason}`,
    "",
    ...evidenceLines,
    "",
    "## Desired Outcome",
    "",
    "Repair the reviewer prompt, artifact writer, metric extraction, or review",
    "workflow so accepted work leaves enough inspectable evidence for later",
    "critics and operators without blocking every concise valid approval.",
    "",
    "## Constraints",
    "",
    "- Build on existing review-scrutiny artifacts and report aggregation.",
    "- Do not add another reviewer, hidden reasoning trace, or audit store.",
    "- Do not create one task per thin acceptance; keep this repair anchored to",
    "  the stable pattern fingerprint above.",
    "- Treat absent metrics and unsupported legacy artifacts as context, not",
    "  standalone proof of poor review.",
    "- Keep cost fields out of autonomy-facing outputs.",
    "",
    "## Product / Safety Link",
    "",
    "This Meta repair supports the Product claim that KOTA's autonomous work can",
    "be trusted from run artifacts, and the Safety concern that agent-authored",
    "code should not be silently accepted as reviewer workload or habituation",
    "rises.",
    "",
    "## Done When",
    "",
    "- Fresh review-scrutiny windows no longer trigger this pattern fingerprint,",
    "  or the detector thresholds/fingerprints are deliberately adjusted with",
    "  focused tests and evidence.",
    "- The repaired reviewer path records concrete warnings, findings, cited",
    "  files, evidence ids, follow-up tasks, or another supported scrutiny",
    "  signal when accepting comparable work.",
    "- Operator-facing report or attention output still names future recurring",
    "  thin-acceptance patterns and repair task ids without cost fields.",
    "",
    "## Source / Intent",
    "",
    "Auto-created by `review-scrutiny-escalator` from recent review-scrutiny",
    "artifacts. Repeated thin approvals should become one evidence-backed repair",
    "task instead of remaining only in the operator report.",
    "",
    "## Initiative",
    "",
    "Outcome-aware autonomy governance.",
    "",
    "## Acceptance Evidence",
    "",
    "- Focused test output for the repaired reviewer/artifact path.",
    "- Detector or report fixture showing this pattern no longer crosses the",
    "  escalation gate on fresh evidence.",
    "- Operator-facing report or attention fixture showing future escalations",
    "  include the repair task id without cost fields.",
    "",
    `<!-- review-scrutiny-pattern-fingerprint: ${pattern.fingerprint} -->`,
    `<!-- review-scrutiny-evidence-fingerprint: ${pattern.evidenceFingerprint} -->`,
    "",
  ].join("\n");
}
