import type { RepoTaskClass } from "#modules/repo-tasks/repo-tasks-domain.js";

export type ClassifiedWorkflowGeneratedTask = Exclude<RepoTaskClass, "Unclassified">;

const GENERATED_WORKFLOW_RE =
  /\b(?:Created by|Generated by)\s+([a-z0-9-]+)\s+workflow\b/i;
const FOLLOW_UP_SOURCE_RE = /\bFollow-up from\b/i;

const AREA_CLASSES = new Map<string, ClassifiedWorkflowGeneratedTask>([
  ["client", "Product"],
  ["clients", "Product"],
  ["operator", "Product"],
  ["ui", "Product"],
  ["channel", "Product"],
  ["security", "Safety"],
  ["secrets", "Safety"],
  ["approval", "Safety"],
  ["approval-queue", "Safety"],
  ["guardrails", "Safety"],
  ["injection-defense", "Safety"],
  ["platform", "Platform"],
  ["architecture", "Platform"],
  ["core", "Platform"],
  ["module", "Platform"],
  ["modules", "Platform"],
  ["model-clients", "Platform"],
  ["daemon", "Platform"],
  ["runtime", "Platform"],
  ["mcp", "Platform"],
  ["harness-parity", "Platform"],
  ["eval-harness", "Platform"],
  ["autonomy", "Meta"],
  ["workflow", "Meta"],
  ["workflows", "Meta"],
  ["queue", "Meta"],
  ["tasks", "Meta"],
  ["evaluator", "Meta"],
]);

const TEXT_CLASS_PATTERNS: readonly [
  ClassifiedWorkflowGeneratedTask,
  readonly RegExp[],
][] = [
  [
    "Safety",
    [
      /\bsecurity\b/i,
      /\bsecret\b/i,
      /\bcredential\b/i,
      /\bauth(?:orization|entication)?\b/i,
      /\bapproval\b/i,
      /\bpermission\b/i,
      /\binjection[- ]defen[cs]e\b/i,
      /\bdestructive\b/i,
      /\bsandbox\b/i,
    ],
  ],
  [
    "Product",
    [
      /\bclient\b/i,
      /\boperator[- ]visible\b/i,
      /\bowner[- ]visible\b/i,
      /\bmacOS\b/i,
      /\biOS\b/i,
      /\bmobile\b/i,
      /\bdashboard\b/i,
      /\bCLI\b/i,
      /\btelegram\b/i,
      /\bslack\b/i,
    ],
  ],
  [
    "Meta",
    [
      /\bautonomy\b/i,
      /\bprogress-review(?:er)?\b/i,
      /\bcritic\b/i,
      /\bevaluator\b/i,
      /\brepair[- ]loop\b/i,
      /\bprompt\b/i,
      /\bqueue\b/i,
      /\bbuilder\b/i,
      /\bimprover\b/i,
      /\bdecomposer\b/i,
      /\bexplorer\b/i,
      /\bcalibration\b/i,
    ],
  ],
  [
    "Platform",
    [
      /\bplatform\b/i,
      /\barchitecture\b/i,
      /\bcore\b/i,
      /\bmodule\b/i,
      /\bruntime\b/i,
      /\bdaemon\b/i,
      /\bprotocol\b/i,
      /\bobservability\b/i,
      /\bDLQ\b/i,
      /\bdead[- ]letter\b/i,
      /\bharness\b/i,
      /\bmodel\b/i,
      /\bMCP\b/i,
    ],
  ],
];

function normalizedArea(area: string): string {
  return area.trim().toLowerCase();
}

function classFromText(title: string, summary: string): ClassifiedWorkflowGeneratedTask | null {
  const text = `${title}\n${summary}`;
  for (const [taskClass, patterns] of TEXT_CLASS_PATTERNS) {
    if (patterns.some((pattern) => pattern.test(text))) return taskClass;
  }
  return null;
}

export function workflowNameFromGeneratedTaskBody(body: string): string | null {
  const match = body.match(GENERATED_WORKFLOW_RE);
  return match?.[1]?.toLowerCase() ?? null;
}

export function classifyWorkflowGeneratedTask(args: {
  workflowName: string;
  area: string;
  title: string;
  summary: string;
}): ClassifiedWorkflowGeneratedTask {
  if (args.workflowName.toLowerCase() === "security-review") return "Safety";

  const areaClass = AREA_CLASSES.get(normalizedArea(args.area));
  if (areaClass) return areaClass;

  return classFromText(args.title, args.summary) ?? "Meta";
}

export function classifyStoredWorkflowGeneratedTask(args: {
  area: string;
  title: string;
  summary: string;
  body: string;
}): ClassifiedWorkflowGeneratedTask | null {
  const workflowName = workflowNameFromGeneratedTaskBody(args.body);
  if (workflowName) return classifyWorkflowGeneratedTask({ ...args, workflowName });

  if (!FOLLOW_UP_SOURCE_RE.test(args.body)) return null;

  const areaClass = AREA_CLASSES.get(normalizedArea(args.area));
  return areaClass ?? classFromText(args.title, args.summary);
}
