import Foundation
import SwiftUI
import XCTest
#if os(macOS)
import AppKit
#endif
@testable import KotaShared

/// Rendered evidence for the macOS capture surface. The PNG fixtures mount the
/// real SwiftUI capture views against deterministic `AppState` branches so the
/// consolidation artifact is tied to the shipped menu-bar client surface.
@MainActor
final class CaptureViewRenderedTests: XCTestCase {
    func testWritesCaptureViewRenderedStates() throws {
        guard let output = Self.snapshotOutput() else { return }

        try FileManager.default.createDirectory(
            at: output.imageDirectory,
            withIntermediateDirectories: true
        )

        var lines = [
            "# Rendered macOS CaptureView snapshot",
            "# Generated by CaptureViewRenderedTests.testWritesCaptureViewRenderedStates",
            "surface: clients/apple/Sources/KotaShared/CaptureView.swift",
            "renderer: SwiftUI.ImageRenderer -> PNG",
            "",
        ]

        for scenario in Self.renderScenarios {
            let rendered = try renderScenario(scenario, in: output.imageDirectory)
            lines.append("## \(scenario.id)")
            lines.append("state: \(scenario.summary)")
            lines.append("mount: \(scenario.mount)")
            lines.append("png: \(output.imageDirectory.lastPathComponent)/\(rendered.fileName)")
            lines.append("pixels: \(rendered.width)x\(rendered.height)")
            lines.append("bytes: \(rendered.byteCount)")
            lines.append("")
        }

        try lines.joined(separator: "\n")
            .write(to: output.manifest, atomically: true, encoding: .utf8)
    }

    private struct RenderScenario {
        let id: String
        let summary: String
        let mount: String
        let configure: (AppState) -> Void
        let content: (AppState) -> AnyView
    }

    private struct RenderedPNG {
        let fileName: String
        let width: Int
        let height: Int
        let byteCount: Int
    }

    private struct SnapshotOutput {
        let manifest: URL
        let imageDirectory: URL
    }

    private static var renderScenarios: [RenderScenario] {
        [
            RenderScenario(
                id: "expanded-empty-draft",
                summary: "CaptureExpandedContent renders the draft field, auto/four-target picker, hint field, submit button, and empty-draft guidance.",
                mount: "CaptureExpandedContent().environmentObject(AppState)",
                configure: { state in state.captureDraft = "" },
                content: { _ in AnyView(CaptureExpandedContent()) }
            ),
            RenderScenario(
                id: "expanded-ready-before-submit",
                summary: "CaptureBodyView renders Press Capture to route this note after typing but before submit.",
                mount: "CaptureBodyView().environmentObject(AppState)",
                configure: { state in state.captureDraft = "Remember to call Alice" },
                content: { _ in AnyView(CaptureBodyView()) }
            ),
            RenderScenario(
                id: "expanded-loading",
                summary: "CaptureBodyView renders the capturing spinner while the request is pending.",
                mount: "CaptureBodyView().environmentObject(AppState)",
                configure: { state in
                    state.captureDraft = "Remember to call Alice"
                    state.isLoadingCapture = true
                    state.captureResult = nil
                },
                content: { _ in AnyView(CaptureBodyView()) }
            ),
            RenderScenario(
                id: "success-memory",
                summary: "CaptureBodyView renders the memory success badge and canonical body line.",
                mount: "CaptureBodyView().environmentObject(AppState)",
                configure: { state in
                    state.captureDraft = "Remember to call Alice"
                    state.captureResult = .success(record: .memory(recordId: "mem-1"))
                },
                content: { _ in AnyView(CaptureBodyView()) }
            ),
            RenderScenario(
                id: "success-knowledge",
                summary: "CaptureBodyView renders the knowledge success badge and canonical body line.",
                mount: "CaptureBodyView().environmentObject(AppState)",
                configure: { state in
                    state.captureDraft = "Store this architecture decision"
                    state.captureResult = .success(record: .knowledge(recordId: "kn-1"))
                },
                content: { _ in AnyView(CaptureBodyView()) }
            ),
            RenderScenario(
                id: "success-tasks",
                summary: "CaptureBodyView renders the tasks success badge and filesystem path metadata.",
                mount: "CaptureBodyView().environmentObject(AppState)",
                configure: { state in
                    state.captureDraft = "File the follow-up"
                    state.captureResult = .success(
                        record: .tasks(
                            recordId: "task-x",
                            path: "data/tasks/ready/task-x.md"
                        )
                    )
                },
                content: { _ in AnyView(CaptureBodyView()) }
            ),
            RenderScenario(
                id: "success-inbox",
                summary: "CaptureBodyView renders the inbox success badge and filesystem path metadata.",
                mount: "CaptureBodyView().environmentObject(AppState)",
                configure: { state in
                    state.captureDraft = "Raw morning thought"
                    state.captureResult = .success(
                        record: .inbox(
                            recordId: "inbox-x",
                            path: "data/inbox/x.md"
                        )
                    )
                },
                content: { _ in AnyView(CaptureBodyView()) }
            ),
            RenderScenario(
                id: "ambiguous",
                summary: "CaptureBodyView renders the ambiguous notice, four suggestion chips, and resubmit footnote.",
                mount: "CaptureBodyView().environmentObject(AppState)",
                configure: { state in
                    state.captureDraft = "Something vague"
                    state.captureResult = .ambiguous(suggestions: [.memory, .knowledge, .tasks, .inbox])
                },
                content: { _ in AnyView(CaptureBodyView()) }
            ),
            RenderScenario(
                id: "no-contributors",
                summary: "CaptureBodyView renders the no_contributors unavailable notice.",
                mount: "CaptureBodyView().environmentObject(AppState)",
                configure: { state in
                    state.captureDraft = "Anything"
                    state.captureResult = .noContributors
                },
                content: { _ in AnyView(CaptureBodyView()) }
            ),
            RenderScenario(
                id: "contributor-failed",
                summary: "CaptureBodyView renders contributor_failed with target badge and verbatim daemon message.",
                mount: "CaptureBodyView().environmentObject(AppState)",
                configure: { state in
                    state.captureDraft = "Forced to inbox"
                    state.captureResult = .contributorFailed(
                        target: .inbox,
                        message: "inbox writer cannot reach scope root"
                    )
                },
                content: { _ in AnyView(CaptureBodyView()) }
            ),
            RenderScenario(
                id: "http-error-retry",
                summary: "CaptureBodyView renders daemon HTTP error text and the Retry control.",
                mount: "CaptureBodyView().environmentObject(AppState)",
                configure: { state in
                    state.captureDraft = "Remember to call Alice"
                    state.captureError = "API error 503: capture unavailable"
                    state.captureResult = nil
                },
                content: { _ in AnyView(CaptureBodyView()) }
            ),
        ]
    }

    private func renderScenario(_ scenario: RenderScenario, in directory: URL) throws -> RenderedPNG {
#if os(macOS)
        let state = AppState(startPollingOnInit: false)
        scenario.configure(state)

        let content = scenario.content(state)
            .environmentObject(state)
            .padding(12)
            .frame(width: 620, alignment: .leading)
            .frame(minHeight: 96, alignment: .leading)
            .background(Color(nsColor: .windowBackgroundColor))

        let renderer = ImageRenderer(content: content)
        renderer.proposedSize = ProposedViewSize(width: 620, height: 220)
        renderer.scale = 2

        guard let image = renderer.cgImage else {
            XCTFail("ImageRenderer did not produce a CGImage for \(scenario.id)")
            throw SnapshotError.renderFailed(scenario.id)
        }

        let rep = NSBitmapImageRep(cgImage: image)
        guard let png = rep.representation(using: NSBitmapImageRep.FileType.png, properties: [:]) else {
            XCTFail("NSBitmapImageRep did not produce PNG data for \(scenario.id)")
            throw SnapshotError.renderFailed(scenario.id)
        }

        let url = directory.appendingPathComponent("\(scenario.id).png")
        try png.write(to: url, options: Data.WritingOptions.atomic)
        XCTAssertGreaterThan(png.count, 1_000, "Rendered PNG for \(scenario.id) should not be blank")

        return RenderedPNG(
            fileName: url.lastPathComponent,
            width: image.width,
            height: image.height,
            byteCount: png.count
        )
#else
        throw XCTSkip("CaptureView PNG snapshots are generated by the macOS test host")
#endif
    }

    private enum SnapshotError: Error {
        case renderFailed(String)
    }

    private static func snapshotOutput() -> SnapshotOutput? {
        let env = ProcessInfo.processInfo.environment
        guard let runDir = env["KOTA_RUN_DIR"], !runDir.isEmpty else { return nil }
        let surfaceDirectory = URL(fileURLWithPath: runDir)
            .appendingPathComponent("capture-consolidation")
            .appendingPathComponent("surface-runtime-evidence")
            .appendingPathComponent("macos")
        return SnapshotOutput(
            manifest: surfaceDirectory.appendingPathComponent("capture-view-rendered-states.txt"),
            imageDirectory: surfaceDirectory.appendingPathComponent("capture-view-rendered-states")
        )
    }
}
