import Foundation
import SwiftUI
import XCTest
#if os(macOS)
import AppKit
#endif
@testable import KotaShared

/// Rendered evidence for the shared macOS/iOS digest surface. The PNG fixtures
/// mount the real SwiftUI views that make up `DigestView` against deterministic
/// `AppState` branches, so the consolidation artifact is tied to the shipped
/// client surface rather than a handwritten reconstruction.
@MainActor
final class DigestViewRenderedTests: XCTestCase {
    func testWritesDigestViewRenderedStates() throws {
        guard let output = Self.snapshotOutput() else { return }

        try FileManager.default.createDirectory(
            at: output.imageDirectory,
            withIntermediateDirectories: true
        )

        var lines = [
            "# Rendered macOS DigestView snapshot",
            "# Generated by DigestViewRenderedTests.testWritesDigestViewRenderedStates",
            "surface: clients/apple/Sources/KotaShared/DigestView.swift",
            "renderer: SwiftUI.ImageRenderer -> PNG",
            "",
        ]

        for scenario in Self.renderScenarios {
            let rendered = try renderScenario(scenario, in: output.imageDirectory)
            lines.append("## \(scenario.id)")
            lines.append("state: \(scenario.summary)")
            lines.append("mount: \(scenario.mount)")
            lines.append("png: \(output.imageDirectory.lastPathComponent)/\(rendered.fileName)")
            lines.append("pixels: \(rendered.width)x\(rendered.height)")
            lines.append("bytes: \(rendered.byteCount)")
            lines.append("")
        }

        try lines.joined(separator: "\n")
            .write(to: output.manifest, atomically: true, encoding: .utf8)
    }

    private struct RenderScenario {
        let id: String
        let summary: String
        let mount: String
        let configure: (AppState) -> Void
        let content: (AppState) -> AnyView
    }

    private struct RenderedPNG {
        let fileName: String
        let width: Int
        let height: Int
        let byteCount: Int
    }

    private struct SnapshotOutput {
        let manifest: URL
        let imageDirectory: URL
    }

    private static var renderScenarios: [RenderScenario] {
        [
            RenderScenario(
                id: "collapsed-active-header",
                summary: "DigestView collapsed header renders the active badge from data.quiet=false",
                mount: "DigestView().environmentObject(AppState)",
                configure: { state in state.content.digest = activeDigest },
                content: { _ in AnyView(DigestView()) }
            ),
            RenderScenario(
                id: "collapsed-quiet-header",
                summary: "DigestView collapsed header renders the quiet-window badge from data.quiet=true",
                mount: "DigestView().environmentObject(AppState)",
                configure: { state in state.content.digest = quietDigest },
                content: { _ in AnyView(DigestView()) }
            ),
            RenderScenario(
                id: "expanded-loading",
                summary: "DigestExpandedContent renders Loading before the first payload",
                mount: "DigestExpandedContent().environmentObject(AppState)",
                configure: { state in
                    state.content.isLoadingDigest = true
                    state.content.digest = nil
                },
                content: { _ in AnyView(DigestExpandedContent()) }
            ),
            RenderScenario(
                id: "expanded-active-body",
                summary: "DigestBodyView renders the active daemon text body and Refresh control",
                mount: "DigestBodyView(digest: activeDigest).environmentObject(AppState)",
                configure: { state in state.content.digest = activeDigest },
                content: { _ in AnyView(DigestBodyView(digest: activeDigest)) }
            ),
            RenderScenario(
                id: "expanded-quiet-body",
                summary: "DigestBodyView renders the quiet daemon text body",
                mount: "DigestBodyView(digest: quietDigest).environmentObject(AppState)",
                configure: { state in state.content.digest = quietDigest },
                content: { _ in AnyView(DigestBodyView(digest: quietDigest)) }
            ),
            RenderScenario(
                id: "expanded-refreshing",
                summary: "DigestBodyView renders Refreshing while a cached digest refreshes",
                mount: "DigestBodyView(digest: activeDigest).environmentObject(AppState)",
                configure: { state in
                    state.content.digest = activeDigest
                    state.content.isLoadingDigest = true
                },
                content: { _ in AnyView(DigestBodyView(digest: activeDigest)) }
            ),
            RenderScenario(
                id: "expanded-error-retry",
                summary: "DigestErrorView renders the daemon error and Retry control",
                mount: "DigestErrorView(message:).environmentObject(AppState)",
                configure: { state in
                    state.content.digest = nil
                    state.content.digestError = "API error 503: digest unavailable"
                },
                content: { state in
                    AnyView(DigestErrorView(message: state.content.digestError ?? "missing error"))
                }
            ),
            RenderScenario(
                id: "expanded-empty-cache",
                summary: "DigestExpandedContent renders Tap to load digest before first load",
                mount: "DigestExpandedContent().environmentObject(AppState)",
                configure: { _ in },
                content: { _ in AnyView(DigestExpandedContent()) }
            ),
        ]
    }

    private static let activeDigest = DigestResponse(
        data: DailyDigestData(
            windowStartedAt: "2026-04-25T08:00:00.000Z",
            windowEndedAt: "2026-04-26T08:00:00.000Z",
            builderCommits: [
                DigestBuilderCommitItem(
                    runId: "r-1",
                    taskId: "task-foo",
                    taskTitle: "Add foo",
                    commitSubject: "Add foo",
                    durationMs: 60_000
                ),
            ],
            explorerAdditions: [],
            decomposerSplits: [],
            blockedPromoterMoves: [],
            failedMonitoredRuns: [],
            pendingOwnerQuestions: [],
            agingOperatorCaptures: [],
            queueDelta: DigestQueueDelta(
                current: DigestQueueCounts(backlog: 0, ready: 1, doing: 0, blocked: 8),
                previous: nil,
                delta: DigestQueueCountDelta(backlog: nil, ready: nil, doing: nil, blocked: nil)
            ),
            quiet: false
        ),
        text: "Daily digest 2026-04-26\n- builder committed: Add foo"
    )

    private static let quietDigest = DigestResponse(
        data: DailyDigestData(
            windowStartedAt: "2026-04-25T08:00:00.000Z",
            windowEndedAt: "2026-04-26T08:00:00.000Z",
            builderCommits: [],
            explorerAdditions: [],
            decomposerSplits: [],
            blockedPromoterMoves: [],
            failedMonitoredRuns: [],
            pendingOwnerQuestions: [],
            agingOperatorCaptures: [],
            queueDelta: DigestQueueDelta(
                current: DigestQueueCounts(backlog: 0, ready: 0, doing: 0, blocked: 0),
                previous: nil,
                delta: DigestQueueCountDelta(backlog: nil, ready: nil, doing: nil, blocked: nil)
            ),
            quiet: true
        ),
        text: "Daily digest 2026-04-26\n(quiet window - nothing to report)"
    )

    private func renderScenario(_ scenario: RenderScenario, in directory: URL) throws -> RenderedPNG {
#if os(macOS)
        let state = AppState(startPollingOnInit: false)
        scenario.configure(state)

        let content = scenario.content(state)
            .environmentObject(state)
            .padding(12)
            .frame(width: 520, alignment: .leading)
            .frame(minHeight: 88, alignment: .leading)
            .background(Color(nsColor: .windowBackgroundColor))

        let renderer = ImageRenderer(content: content)
        renderer.proposedSize = ProposedViewSize(width: 520, height: 180)
        renderer.scale = 2

        guard let image = renderer.cgImage else {
            XCTFail("ImageRenderer did not produce a CGImage for \(scenario.id)")
            throw SnapshotError.renderFailed(scenario.id)
        }

        let rep = NSBitmapImageRep(cgImage: image)
        guard let png = rep.representation(using: NSBitmapImageRep.FileType.png, properties: [:]) else {
            XCTFail("NSBitmapImageRep did not produce PNG data for \(scenario.id)")
            throw SnapshotError.renderFailed(scenario.id)
        }

        let url = directory.appendingPathComponent("\(scenario.id).png")
        try png.write(to: url, options: Data.WritingOptions.atomic)
        XCTAssertGreaterThan(png.count, 1_000, "Rendered PNG for \(scenario.id) should not be blank")

        return RenderedPNG(
            fileName: url.lastPathComponent,
            width: image.width,
            height: image.height,
            byteCount: png.count
        )
#else
        throw XCTSkip("DigestView PNG snapshots are generated by the macOS test host")
#endif
    }

    private enum SnapshotError: Error {
        case renderFailed(String)
    }

    private static func snapshotOutput() -> SnapshotOutput? {
        let env = ProcessInfo.processInfo.environment
        guard let runDir = env["KOTA_RUN_DIR"], !runDir.isEmpty else { return nil }
        let surfaceDirectory = URL(fileURLWithPath: runDir)
            .appendingPathComponent("digest-consolidation")
            .appendingPathComponent("surface-runtime-evidence")
            .appendingPathComponent("macos")
        return SnapshotOutput(
            manifest: surfaceDirectory.appendingPathComponent("digest-view-rendered-states.txt"),
            imageDirectory: surfaceDirectory.appendingPathComponent("digest-view-rendered-states")
        )
    }
}
