import Foundation
import SwiftUI
import XCTest
#if os(macOS)
import AppKit
#endif
@testable import KotaShared

/// Coverage for the shared macOS/iOS `HistoryBodyView` data shape and rendered
/// macOS evidence. The PNG fixtures mount the real SwiftUI body against
/// deterministic `AppState` branches so the review artifact is not a prose-only
/// reconstruction of the surface.
@MainActor
final class HistoryViewTests: XCTestCase {
    private let decoder = JSONDecoder()

    func testHistorySearchResponseDecodesPopulatedConversations() throws {
        let json = #"""
        {"ok": true, "conversations": [
          {
            "id": "hist-1",
            "title": "Release planning",
            "createdAt": "2026-06-15T09:10:00.000Z",
            "updatedAt": "2026-06-15T09:20:00.000Z",
            "model": "test-model",
            "messageCount": 3,
            "cwd": "/tmp/scope",
            "source": "user"
          },
          {
            "id": "hist-22",
            "title": "Operator review",
            "createdAt": "2026-06-15T10:00:00.000Z",
            "updatedAt": "2026-06-15T10:45:00.000Z",
            "model": "test-model",
            "messageCount": 11,
            "cwd": "/tmp/scope",
            "source": "action"
          }
        ]}
        """#.data(using: .utf8)!
        let response = try decoder.decode(HistorySearchResponse.self, from: json)
        guard case .success(let conversations) = response else {
            XCTFail("expected populated success branch")
            return
        }
        XCTAssertEqual(conversations.count, 2)
        XCTAssertEqual(conversations[0].id, "hist-1")
        XCTAssertEqual(conversations[0].source, .user)
        XCTAssertEqual(conversations[1].source, .action)
    }

    func testRenderHistorySearchPlainMatchesSharedLineShape() {
        XCTAssertEqual(
            renderHistorySearchPlain(Self.sampleConversations),
            """
            hist-1   2026-06-15 09:20     3 msgs  Release planning
            hist-22  2026-06-15 10:45    11 msgs  Operator review
            """
        )
    }

    func testHistorySearchResponseDecodesEmptyConversations() throws {
        let json = #"{"ok": true, "conversations": []}"#.data(using: .utf8)!
        let response = try decoder.decode(HistorySearchResponse.self, from: json)
        guard case .success(let conversations) = response else {
            XCTFail("expected empty success branch")
            return
        }
        XCTAssertTrue(conversations.isEmpty)
    }

    func testHistorySearchResponseDecodesSemanticUnavailable() throws {
        let json = #"{"ok": false, "reason": "semantic_unavailable"}"#.data(using: .utf8)!
        let response = try decoder.decode(HistorySearchResponse.self, from: json)
        XCTAssertEqual(response, .semanticUnavailable)
    }

    func testHistorySearchResponseRejectsUnknownReason() {
        let json = #"{"ok": false, "reason": "something_else"}"#.data(using: .utf8)!
        XCTAssertThrowsError(try decoder.decode(HistorySearchResponse.self, from: json))
    }

    func testEmptyQueryPredicateMatchesViewAndLoader() {
        let blankQueries = ["", "   ", "\t\n", " \n "]
        for query in blankQueries {
            XCTAssertTrue(
                query.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
                "query \(query.debugDescription) should trim to empty"
            )
        }

        let nonBlankQueries = ["fan-out", "  fan-out  ", "history"]
        for query in nonBlankQueries {
            XCTAssertFalse(
                query.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
                "query \(query.debugDescription) should remain non-empty after trim"
            )
        }
    }

    func testWritesHistoryViewRenderedStates() throws {
        guard let output = Self.snapshotOutput() else { return }

        try FileManager.default.createDirectory(
            at: output.imageDirectory,
            withIntermediateDirectories: true
        )

        var lines = [
            "# Rendered macOS HistoryView snapshot",
            "# Generated by HistoryViewTests.testWritesHistoryViewRenderedStates",
            "surface: clients/apple/Sources/KotaShared/HistoryView.swift",
            "mount: HistoryBodyView().environmentObject(AppState)",
            "renderer: SwiftUI.ImageRenderer -> PNG",
            "",
        ]

        for scenario in Self.renderScenarios {
            let rendered = try renderScenario(scenario, in: output.imageDirectory)
            lines.append("## \(scenario.id)")
            lines.append("state: \(scenario.summary)")
            lines.append("png: \(output.imageDirectory.lastPathComponent)/\(rendered.fileName)")
            lines.append("pixels: \(rendered.width)x\(rendered.height)")
            lines.append("bytes: \(rendered.byteCount)")
            lines.append("")
        }

        try lines.joined(separator: "\n")
            .write(to: output.manifest, atomically: true, encoding: .utf8)
    }

    private static let sampleConversations = [
        ConversationRecord(
            id: "hist-1",
            title: "Release planning",
            createdAt: "2026-06-15T09:10:00.000Z",
            updatedAt: "2026-06-15T09:20:00.000Z",
            model: "test-model",
            messageCount: 3,
            cwd: "/tmp/scope",
            source: .user
        ),
        ConversationRecord(
            id: "hist-22",
            title: "Operator review",
            createdAt: "2026-06-15T10:00:00.000Z",
            updatedAt: "2026-06-15T10:45:00.000Z",
            model: "test-model",
            messageCount: 11,
            cwd: "/tmp/scope",
            source: .action
        ),
    ]

    private struct RenderScenario {
        let id: String
        let summary: String
        let configure: (AppState) -> Void
    }

    private struct RenderedPNG {
        let fileName: String
        let width: Int
        let height: Int
        let byteCount: Int
    }

    private struct SnapshotOutput {
        let manifest: URL
        let imageDirectory: URL
    }

    private static var renderScenarios: [RenderScenario] {
        [
            RenderScenario(
                id: "empty-query",
                summary: "historyQuery is blank; HistoryBodyView renders the empty-query hint",
                configure: { state in
                    state.content.historyQuery = ""
                }
            ),
            RenderScenario(
                id: "loading",
                summary: "isLoadingHistory is true before the first result arrives",
                configure: { state in
                    state.content.historyQuery = "release"
                    state.content.isLoadingHistory = true
                    state.content.historyResult = nil
                }
            ),
            RenderScenario(
                id: "populated",
                summary: "success response contains two conversations",
                configure: { state in
                    state.content.historyQuery = "release"
                    state.content.historyResult = .success(conversations: sampleConversations)
                }
            ),
            RenderScenario(
                id: "empty-results",
                summary: "success response contains no conversations",
                configure: { state in
                    state.content.historyQuery = "missing"
                    state.content.historyResult = .success(conversations: [])
                }
            ),
            RenderScenario(
                id: "semantic-unavailable",
                summary: "daemon returns the semantic_unavailable result arm",
                configure: { state in
                    state.content.historyQuery = "release"
                    state.content.historyResult = .semanticUnavailable
                }
            ),
            RenderScenario(
                id: "error-retry",
                summary: "historyError is set and the retry body is mounted",
                configure: { state in
                    state.content.historyQuery = "release"
                    state.content.historyError = "503 Service Unavailable"
                }
            ),
            RenderScenario(
                id: "after-query-before-submit",
                summary: "non-empty query has no result, loading flag, or error yet",
                configure: { state in
                    state.content.historyQuery = "release"
                }
            ),
        ]
    }

    private func renderScenario(_ scenario: RenderScenario, in directory: URL) throws -> RenderedPNG {
#if os(macOS)
        let state = AppState(startPollingOnInit: false)
        scenario.configure(state)

        let content = HistoryBodyView()
            .environmentObject(state)
            .padding(12)
            .frame(width: 520, alignment: .leading)
            .frame(minHeight: 72, alignment: .leading)
            .background(Color(nsColor: .textBackgroundColor))

        let renderer = ImageRenderer(content: content)
        renderer.proposedSize = ProposedViewSize(width: 520, height: 120)
        renderer.scale = 2

        guard let image = renderer.cgImage else {
            XCTFail("ImageRenderer did not produce a CGImage for \(scenario.id)")
            throw SnapshotError.renderFailed(scenario.id)
        }

        let rep = NSBitmapImageRep(cgImage: image)
        guard let png = rep.representation(using: NSBitmapImageRep.FileType.png, properties: [:]) else {
            XCTFail("NSBitmapImageRep did not produce PNG data for \(scenario.id)")
            throw SnapshotError.renderFailed(scenario.id)
        }

        let url = directory.appendingPathComponent("\(scenario.id).png")
        try png.write(to: url, options: Data.WritingOptions.atomic)
        XCTAssertGreaterThan(png.count, 1_000, "Rendered PNG for \(scenario.id) should not be blank")

        return RenderedPNG(
            fileName: url.lastPathComponent,
            width: image.width,
            height: image.height,
            byteCount: png.count
        )
#else
        throw XCTSkip("HistoryBodyView PNG snapshots are generated by the macOS test host")
#endif
    }

    private enum SnapshotError: Error {
        case renderFailed(String)
    }

    private static func snapshotOutput() -> SnapshotOutput? {
        let env = ProcessInfo.processInfo.environment
        guard let runDir = env["KOTA_RUN_DIR"], !runDir.isEmpty else { return nil }
        let surfaceDirectory = URL(fileURLWithPath: runDir)
            .appendingPathComponent("history-consolidation")
            .appendingPathComponent("surfaces")
            .appendingPathComponent("macos")
        return SnapshotOutput(
            manifest: surfaceDirectory.appendingPathComponent("history-view-rendered-states.txt"),
            imageDirectory: surfaceDirectory.appendingPathComponent("history-view-rendered-states")
        )
    }
}
