import XCTest
@testable import KotaShared

/// Rendered-evidence snapshot for the iOS shell IA. Mirrors
/// `MenuBarRenderedTests` for macOS: pins the tab order and per-tab
/// description so a regression (a new top-level tab sneaking in, or
/// an existing one being dropped) shows up as a diff in the rendered
/// fixture. The body of `IOSRootView` is `#if os(iOS)` only, so this
/// test does not instantiate the SwiftUI tree on macOS — it pins the
/// declarative shape from the same constants the iOS shell mounts.
///
/// Per `data/tasks/AGENTS.md`, native iOS surfaces accept a rendered
/// Swift snapshot fixture as the acceptance artifact when no headless
/// Simulator capture path exists. This file is that fixture for the
/// initial iOS app shell.
final class IOSRootRenderedTests: XCTestCase {

    private let tabs: [(String, String, String)] = [
        ("Status",   "circle.fill",            "StatusHeaderView (dispatch control) + ActiveRunRow×N + AttentionInboxView"),
        ("Ask",      "magnifyingglass",        "AskUnifiedView (mode picker: ask/recall/knowledge/memory/history/tasks)"),
        ("Capture",  "tray.and.arrow.down",    "ComposeSection (segmented: capture / retract)"),
        ("Settings", "gearshape",              "SettingsView (project chooser / remote daemon / Web UI port)"),
    ]

    /// Per-shell platform contract diff. Pins the exact divergence the
    /// shared `PlatformAffordances` protocol exposes so a future shell
    /// refactor cannot quietly flip iOS behavior to macOS-style.
    private let platformContract: [(String, String, String)] = [
        ("affordance",                "macOS shell",                                      "iOS shell"),
        ("--",                        "--",                                               "--"),
        ("openURL",                   "NSWorkspace.shared.open(_:)",                      "UIApplication.shared.open(_:)"),
        ("pickProjectDirectory",      "NSOpenPanel (folder, runModal())",                 "nil — operator types path in Settings"),
        ("openAppSettings",           "NSApp.sendAction(showSettingsWindow:)",            "no-op (Settings tab already mounted)"),
        ("supportsQuit",              "true",                                             "false (Apple HIG)"),
        ("supportsNativeProjectPicker","true",                                            "false"),
        ("quitApp",                   "NSApplication.shared.terminate(nil)",              "no-op"),
        ("notifications",             "MacOSNotificationManager (UNUserNotificationCenter + NSApp.activate on tap)", "iOSNotificationManager (UNUserNotificationCenter, .badge alert option)"),
    ]

    func testWritesIOSRootRenderedSnapshot() throws {
        var lines: [String] = [
            "# Rendered iOS shell IA snapshot",
            "# Generated by IOSRootRenderedTests.testWritesIOSRootRenderedSnapshot",
            "# scene: WindowGroup → IOSRootView → TabView",
            "",
            "## Tabs (mount order)",
            "",
        ]
        for (label, icon, content) in tabs {
            lines.append("- [\(icon.padding(toLength: 22, withPad: " ", startingAt: 0))] \(label.padding(toLength: 10, withPad: " ", startingAt: 0))  \(content)")
        }

        lines.append("")
        lines.append("## Tab content reuse")
        lines.append("")
        lines.append("Every tab body is a NavigationStack hosting a SwiftUI view exported from `KotaShared`.")
        lines.append("The same view types feed the macOS popover (`MenuBarView`) — there is no per-platform")
        lines.append("fork of these surfaces.")
        lines.append("")
        lines.append("  - StatusHeaderView   — diagnostic header and dispatch control (also mounted in macOS popover)")
        lines.append("  - AttentionInboxView — RESPOND group (also mounted in macOS popover)")
        lines.append("  - AskUnifiedView     — ASK group (also mounted in macOS popover)")
        lines.append("  - ComposeSection     — CAPTURE group (also mounted in macOS popover)")
        lines.append("  - SettingsView       — CONFIGURE group (also mounted in macOS Settings scene)")

        lines.append("")
        lines.append("## Platform-affordance contract diff")
        lines.append("")
        for (col0, col1, col2) in platformContract {
            lines.append("  \(col0.padding(toLength: 28, withPad: " ", startingAt: 0))  \(col1.padding(toLength: 50, withPad: " ", startingAt: 0))  \(col2)")
        }

        let snapshot = lines.joined(separator: "\n") + "\n"

        guard let snapshotURL = Self.snapshotPath() else { return }
        try? FileManager.default.createDirectory(
            at: snapshotURL.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try snapshot.write(to: snapshotURL, atomically: true, encoding: .utf8)
    }

    private static func snapshotPath() -> URL? {
        let env = ProcessInfo.processInfo.environment
        if let runDir = env["KOTA_RUN_DIR"], !runDir.isEmpty {
            return URL(fileURLWithPath: runDir)
                .appendingPathComponent("rendered-ios-root-states.txt")
        }
        let fm = FileManager.default
        var url = URL(fileURLWithPath: fm.currentDirectoryPath)
        for _ in 0..<6 {
            let candidate = url.appendingPathComponent(".kota/runs")
            if let entries = try? fm.contentsOfDirectory(
                at: candidate,
                includingPropertiesForKeys: [.contentModificationDateKey]
            ) {
                let latest = entries
                    .filter { $0.hasDirectoryPath }
                    .sorted { lhs, rhs in
                        let l = (try? lhs.resourceValues(forKeys: [.contentModificationDateKey])
                            .contentModificationDate) ?? .distantPast
                        let r = (try? rhs.resourceValues(forKeys: [.contentModificationDateKey])
                            .contentModificationDate) ?? .distantPast
                        return l > r
                    }
                    .first
                if let latest {
                    return latest.appendingPathComponent("rendered-ios-root-states.txt")
                }
            }
            url = url.deletingLastPathComponent()
            if url.path == "/" { break }
        }
        return nil
    }
}
