import XCTest
@testable import KotaShared

/// Rendered-evidence snapshot for the project selector mounted in the
/// macOS menu-bar popover (`MenuBarView`) and the iOS Status tab
/// (`IOSRootView`). Per `data/tasks/AGENTS.md`, native shells accept a
/// committed Swift snapshot fixture as the acceptance artifact when no
/// headless capture path exists. This file is that fixture for the
/// initial multi-project picker.
///
/// Three states are pinned:
///
///   1. **Single-project KOTA-on-itself.** The picker is hidden so the
///      pre-multi-project experience is byte-identical.
///   2. **Multi-project, default selected.** The picker renders one
///      chip per configured project and highlights `defaultProjectId`.
///   3. **Multi-project, switched.** The operator picked the second
///      project; `setActiveProjectId` must immediately reseat the
///      picker without waiting for a refresh round trip.
@MainActor
final class ProjectSelectorRenderedTests: XCTestCase {

    private let singleProject = ProjectRegistryProjection(
        defaultProjectId: "p-kota",
        projects: [
            ConfiguredProjectEntry(
                projectId: "p-kota",
                projectDir: "/Users/operator/projects/kota",
                displayName: "kota"
            )
        ]
    )

    private let multiProject = ProjectRegistryProjection(
        defaultProjectId: "p-kota",
        projects: [
            ConfiguredProjectEntry(
                projectId: "p-kota",
                projectDir: "/Users/operator/projects/kota",
                displayName: "kota"
            ),
            ConfiguredProjectEntry(
                projectId: "p-side",
                projectDir: "/Users/operator/projects/side-project",
                displayName: "side-project"
            ),
        ]
    )

    private func makeState(projection: ProjectRegistryProjection, active: String?) -> AppState {
        UserDefaults.standard.removeObject(forKey: "projectDirectory")
        UserDefaults.standard.removeObject(forKey: "remoteDaemonURL")
        let state = AppState(
            client: nil,
            notifications: InertNotificationManager(),
            startPollingOnInit: false
        )
        state.identity = ClientIdentity(
            projectName: "kota",
            projectDir: "/Users/operator/projects/kota",
            projects: projection,
            daemonVersion: "0.1.0",
            pid: 12345,
            startedAt: "2026-04-29T01:00:00.000Z",
            dashboard: .available(path: "/")
        )
        if let active {
            state.reconcileActiveProjectId(with: projection)
            if active != projection.defaultProjectId {
                state.setActiveProjectId(active)
            }
        }
        return state
    }

    func testWritesProjectSelectorRenderedSnapshot() throws {
        let single = makeState(projection: singleProject, active: nil)
        let multiDefault = makeState(projection: multiProject, active: "p-kota")
        let multiSwitched = makeState(projection: multiProject, active: nil)
        multiSwitched.setActiveProjectId("p-side")

        var lines: [String] = [
            "# Rendered ProjectSelector states",
            "# Generated by ProjectSelectorRenderedTests.testWritesProjectSelectorRenderedSnapshot",
            "# Surface: KotaShared/ProjectSelectorView.swift (mounted in MenuBarView + IOSRootView)",
            "",
        ]
        lines.append(renderState(label: "single-project (KOTA-on-itself)", state: single))
        lines.append("")
        lines.append(renderState(label: "multi-project (default selected)", state: multiDefault))
        lines.append("")
        lines.append(renderState(label: "multi-project (operator switched to p-side)", state: multiSwitched))

        // Sanity assertions: the snapshot is only useful if it
        // captures the same selection state the AppState reports.
        XCTAssertNil(single.activeProjectId)
        XCTAssertEqual(multiDefault.activeProjectId, "p-kota")
        XCTAssertEqual(multiSwitched.activeProjectId, "p-side")

        let snapshot = lines.joined(separator: "\n") + "\n"
        guard let url = Self.snapshotPath() else { return }
        try? FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try snapshot.write(to: url, atomically: true, encoding: .utf8)
    }

    private func renderState(label: String, state: AppState) -> String {
        var lines: [String] = []
        lines.append("## \(label)")
        guard let identity = state.identity else {
            lines.append("  (no identity payload)")
            return lines.joined(separator: "\n")
        }
        let entries = identity.projects.projects
        if entries.count <= 1 {
            lines.append("  selector hidden — registry has a single project (\(entries.first?.displayName ?? "<none>"))")
            lines.append("  activeProjectId = \(state.activeProjectId ?? "<nil>")")
            return lines.joined(separator: "\n")
        }
        lines.append("  ┌─ Project ─────────────────────────────────────┐")
        for entry in entries {
            let active = state.activeProjectId == entry.projectId
            let marker = active ? "●" : "○"
            let line = "  │ \(marker) \(entry.displayName.padding(toLength: 18, withPad: " ", startingAt: 0))  \(entry.projectId.padding(toLength: 24, withPad: " ", startingAt: 0)) │"
            lines.append(line)
        }
        lines.append("  └────────────────────────────────────────────────┘")
        lines.append("  activeProjectId = \(state.activeProjectId ?? "<nil>")")
        return lines.joined(separator: "\n")
    }

    private static func snapshotPath() -> URL? {
        let env = ProcessInfo.processInfo.environment
        if let runDir = env["KOTA_RUN_DIR"], !runDir.isEmpty {
            return URL(fileURLWithPath: runDir)
                .appendingPathComponent("rendered-project-selector-states.txt")
        }
        let fm = FileManager.default
        var url = URL(fileURLWithPath: fm.currentDirectoryPath)
        for _ in 0..<6 {
            let candidate = url.appendingPathComponent(".kota/runs")
            if let entries = try? fm.contentsOfDirectory(
                at: candidate,
                includingPropertiesForKeys: [.contentModificationDateKey]
            ) {
                let latest = entries
                    .filter { $0.hasDirectoryPath }
                    .sorted { lhs, rhs in
                        let l = (try? lhs.resourceValues(forKeys: [.contentModificationDateKey])
                            .contentModificationDate) ?? .distantPast
                        let r = (try? rhs.resourceValues(forKeys: [.contentModificationDateKey])
                            .contentModificationDate) ?? .distantPast
                        return l > r
                    }
                    .first
                if let latest {
                    return latest.appendingPathComponent("rendered-project-selector-states.txt")
                }
            }
            url = url.deletingLastPathComponent()
            if url.path == "/" { break }
        }
        return nil
    }
}
