import XCTest
@testable import KotaShared

/// Rendered-evidence snapshot for the scope selector mounted in the
/// macOS menu-bar popover (`MenuBarView`) and the iOS Status tab
/// (`IOSRootView`). Per `data/tasks/AGENTS.md`, native shells accept a
/// committed Swift snapshot fixture as the acceptance artifact when no
/// headless capture path exists. This file is that fixture for the
/// initial multi-scope picker.
///
/// Three states are pinned:
///
///   1. **Single-scope KOTA-on-itself.** The picker is hidden so the
///      pre-multi-scope experience is byte-identical.
///   2. **Multi-scope, default selected.** The picker renders one
///      chip per configured scope and highlights `defaultScopeId`.
///   3. **Multi-scope, switched.** The operator picked the second
///      scope; `setActiveScopeId` must immediately reseat the
///      picker without waiting for a refresh round trip.
@MainActor
final class ScopeSelectorRenderedTests: XCTestCase {

    private let singleScope = makeScopeRegistry(
        defaultScopeId: "p-kota",
        directoryScopes: [
            directoryScope(
                scopeId: "p-kota",
                displayName: "kota",
                directoryRoot: "/Users/operator/projects/kota"
                )
        ]
    )

    private let multiScope = makeScopeRegistry(
        defaultScopeId: "p-kota",
        directoryScopes: [
            directoryScope(
                scopeId: "p-kota",
                displayName: "kota",
                directoryRoot: "/Users/operator/projects/kota"
                ),
            directoryScope(
                scopeId: "p-side",
                displayName: "side-scope",
                directoryRoot: "/Users/operator/projects/side-scope"
                ),
        ]
    )

    private func makeState(projection: ScopeRegistryProjection, active: String?) -> AppState {
        UserDefaults.standard.removeObject(forKey: "scopeDirectory")
        UserDefaults.standard.removeObject(forKey: "remoteDaemonURL")
        let state = AppState(
            client: nil,
            notifications: InertNotificationManager(),
            startPollingOnInit: false
        )
        state.connection.identity = ClientIdentity(
            scopeName: "kota",
            scopeRoot: "/Users/operator/projects/kota",
            scopeRegistry: projection,
            daemonVersion: "0.1.0",
            pid: 12345,
            startedAt: "2026-04-29T01:00:00.000Z",
            dashboard: .available(path: "/")
        )
        if let active {
            state.reconcileActiveScopeId(with: projection)
            if active != projection.defaultScopeId {
                state.setActiveScopeId(active)
            }
        }
        return state
    }

    func testWritesScopeSelectorRenderedSnapshot() throws {
        let single = makeState(projection: singleScope, active: nil)
        let multiDefault = makeState(projection: multiScope, active: "p-kota")
        let multiSwitched = makeState(projection: multiScope, active: nil)
        multiSwitched.setActiveScopeId("p-side")

        var lines: [String] = [
            "# Rendered ScopeSelector states",
            "# Generated by ScopeSelectorRenderedTests.testWritesScopeSelectorRenderedSnapshot",
            "# Surface: KotaShared/ScopeSelectorView.swift (mounted in MenuBarView + IOSRootView)",
            "",
        ]
        lines.append(renderState(label: "single-scope (KOTA-on-itself)", state: single))
        lines.append("")
        lines.append(renderState(label: "multi-scope (default selected)", state: multiDefault))
        lines.append("")
        lines.append(renderState(label: "multi-scope (operator switched to p-side)", state: multiSwitched))

        // Sanity assertions: the snapshot is only useful if it
        // captures the same selection state the AppState reports.
        XCTAssertNil(single.connection.activeScopeId)
        XCTAssertEqual(multiDefault.connection.activeScopeId, "p-kota")
        XCTAssertEqual(multiSwitched.connection.activeScopeId, "p-side")

        let snapshot = lines.joined(separator: "\n") + "\n"
        guard let url = Self.snapshotPath() else { return }
        try? FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try snapshot.write(to: url, atomically: true, encoding: .utf8)
    }

    private func renderState(label: String, state: AppState) -> String {
        var lines: [String] = []
        lines.append("## \(label)")
        guard let identity = state.connection.identity else {
            lines.append("  (no identity payload)")
            return lines.joined(separator: "\n")
        }
        let entries = identity.scopeRegistry.scopes
        if entries.count <= 1 {
            lines.append("  selector hidden — registry has a single scope (\(entries.first?.displayName ?? "<none>"))")
            lines.append("  activeScopeId = \(state.connection.activeScopeId ?? "<nil>")")
            return lines.joined(separator: "\n")
        }
        lines.append("  ┌─ Scope ─────────────────────────────────────┐")
        for entry in entries {
            let active = state.connection.activeScopeId == entry.scopeId
            let marker = active ? "●" : "○"
            let line = "  │ \(marker) \(entry.displayName.padding(toLength: 18, withPad: " ", startingAt: 0))  \(entry.scopeId.padding(toLength: 24, withPad: " ", startingAt: 0)) │"
            lines.append(line)
        }
        lines.append("  └────────────────────────────────────────────────┘")
        lines.append("  activeScopeId = \(state.connection.activeScopeId ?? "<nil>")")
        return lines.joined(separator: "\n")
    }

    private static func snapshotPath() -> URL? {
        let env = ProcessInfo.processInfo.environment
        if let runDir = env["KOTA_RUN_DIR"], !runDir.isEmpty {
            return URL(fileURLWithPath: runDir)
                .appendingPathComponent("rendered-scope-selector-states.txt")
        }
        let fm = FileManager.default
        var url = URL(fileURLWithPath: fm.currentDirectoryPath)
        for _ in 0..<6 {
            let candidate = url.appendingPathComponent(".kota/runs")
            if let entries = try? fm.contentsOfDirectory(
                at: candidate,
                includingPropertiesForKeys: [.contentModificationDateKey]
            ) {
                let latest = entries
                    .filter { $0.hasDirectoryPath }
                    .sorted { lhs, rhs in
                        let l = (try? lhs.resourceValues(forKeys: [.contentModificationDateKey])
                            .contentModificationDate) ?? .distantPast
                        let r = (try? rhs.resourceValues(forKeys: [.contentModificationDateKey])
                            .contentModificationDate) ?? .distantPast
                        return l > r
                    }
                    .first
                if let latest {
                    return latest.appendingPathComponent("rendered-scope-selector-states.txt")
                }
            }
            url = url.deletingLastPathComponent()
            if url.path == "/" { break }
        }
        return nil
    }
}
