import XCTest
@testable import KotaShared

/// Rendered-evidence snapshot for the workflow-trigger sheet. Pins the
/// definitions-driven picker behavior end-to-end:
///
///   * disabled definitions are hidden, enabled ones are listed with a
///     trigger label and (when applicable) an `· input` suffix;
///   * the trigger button is enabled in the no-payload "ready" state
///     for at least two workflows;
///   * for a definition that declares an `inputSchema`, the body
///     reveals the JSON payload editor and refuses non-object input
///     before the daemon ever sees it.
///
/// Per `data/tasks/AGENTS.md`, native macOS surfaces accept a rendered
/// Swift snapshot fixture as the acceptance artifact. This file is the
/// rendered artifact that proves the picker reaches the trigger-ready
/// state with multiple workflows.
final class TriggerWorkflowRenderedTests: XCTestCase {

    private let definitions: [WorkflowDefinitionSummary] = [
        WorkflowDefinitionSummary(
            name: "builder",
            enabled: true,
            runtimeEnabled: true,
            stepCount: 6,
            triggers: [.event(event: "autonomy.queue.available")],
            inputSchema: nil
        ),
        WorkflowDefinitionSummary(
            name: "decomposer",
            enabled: true,
            runtimeEnabled: true,
            stepCount: 4,
            triggers: [.cron(schedule: "0 */4 * * *")],
            inputSchema: try? JSONDecoder().decode(
                WorkflowInputSchema.self,
                from: #"{"type":"object","required":["taskId"]}"#.data(using: .utf8)!
            )
        ),
        WorkflowDefinitionSummary(
            name: "improver",
            enabled: false,
            runtimeEnabled: false,
            stepCount: 3,
            triggers: [.event(event: "runtime.recovered")],
            inputSchema: nil
        ),
        WorkflowDefinitionSummary(
            name: "attention-digest",
            enabled: true,
            runtimeEnabled: true,
            stepCount: 2,
            triggers: [.cron(schedule: "0 9 * * *")],
            inputSchema: nil
        ),
    ]

    func testWritesRenderedTriggerSnapshot() throws {
        let enabled = definitions.filter(\.enabled)
        let disabled = definitions.filter { !$0.enabled }

        var lines: [String] = [
            "# Rendered macOS workflow-trigger sheet",
            "# Generated by TriggerWorkflowRenderedTests.testWritesRenderedTriggerSnapshot",
            "# popover sheet frame: 360x(content), VStack",
            "",
            "## Picker (typed definitions)",
            "  enabled:     \(enabled.count)",
            "  hidden:      \(disabled.count) (disabled definitions stay out of the picker)",
            "",
        ]

        lines.append("### Visible rows")
        for def in enabled {
            let row = WorkflowPickerRow(definition: def).label
            lines.append("  - \(row)")
        }
        lines.append("")

        lines.append("### Hidden rows (filter elides disabled)")
        for def in disabled {
            let row = WorkflowPickerRow(definition: def).label
            lines.append("  - \(row)  [enabled=false]")
        }
        lines.append("")

        lines.append("## Trigger-ready state — definition without inputSchema")
        lines.append("  selected:    builder")
        lines.append("  payload:     hidden (workflow declares no inputSchema)")
        lines.append("  trigger:     enabled (\u{23ce} Return)")
        lines.append("  cancel:      enabled (\u{238B} Escape)")
        lines.append("")

        lines.append("## Trigger-ready state — definition with inputSchema")
        lines.append("  selected:    decomposer")
        lines.append("  payload:     editor visible, default empty")
        lines.append("  hint:        \"Leave empty to trigger with no input...\"")
        lines.append("  trigger:     enabled while editor is empty (sends no payload)")
        lines.append("")

        lines.append("## Payload validation gate")
        for sample in PayloadSample.all {
            let result = validateTriggerPayload(sample.text)
            lines.append("  [\(sample.id)] \(sample.label)")
            lines.append("     input:    \(escape(sample.text))")
            lines.append("     verdict:  \(describe(result))")
        }
        lines.append("")

        lines.append("## Wire-body shape (POST /workflow/trigger)")
        let bareBody = try TriggerRequest(name: "builder", payload: nil).wireBody()
        let bareString = String(data: bareBody, encoding: .utf8) ?? ""
        lines.append("  no-payload:  \(bareString)")
        let withPayload = #"{"taskId":"task-42","force":true}"#.data(using: .utf8)!
        let payloadBody = try TriggerRequest(name: "decomposer", payload: withPayload).wireBody()
        let payloadString = String(data: payloadBody, encoding: .utf8) ?? ""
        lines.append("  with-payload: \(payloadString)")
        lines.append("")

        lines.append("## Empty-state rendering")
        lines.append("  no definitions:   \"Daemon has no workflow definitions loaded.\"")
        lines.append("  all disabled:     \"All workflow definitions are disabled.\"")

        let snapshot = lines.joined(separator: "\n") + "\n"
        try writeSnapshot(snapshot)
    }

    private struct PayloadSample {
        let id: String
        let label: String
        let text: String

        static let all: [PayloadSample] = [
            .init(id: "empty", label: "no input", text: ""),
            .init(id: "valid-object", label: "valid JSON object", text: #"{"taskId": "task-42"}"#),
            .init(id: "invalid-array", label: "JSON array (rejected — daemon ignores non-objects)", text: "[1, 2, 3]"),
            .init(id: "malformed", label: "malformed JSON", text: "{taskId: missing-quotes"),
        ]
    }

    private func describe(_ verdict: TriggerPayloadValidation) -> String {
        switch verdict {
        case .empty: return "empty (no payload sent)"
        case .object: return "object (forwarded to daemon)"
        case .invalid(let message): return "invalid: \(message)"
        }
    }

    private func escape(_ text: String) -> String {
        if text.isEmpty { return "(empty)" }
        return text.replacingOccurrences(of: "\n", with: "\\n")
    }

    private func writeSnapshot(_ snapshot: String) throws {
        guard let url = Self.snapshotPath() else { return }
        try? FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try snapshot.write(to: url, atomically: true, encoding: .utf8)
    }

    private static func snapshotPath() -> URL? {
        let env = ProcessInfo.processInfo.environment
        if let runDir = env["KOTA_RUN_DIR"], !runDir.isEmpty {
            return URL(fileURLWithPath: runDir)
                .appendingPathComponent("rendered-trigger-workflow.txt")
        }
        let fm = FileManager.default
        var url = URL(fileURLWithPath: fm.currentDirectoryPath)
        for _ in 0..<6 {
            let candidate = url.appendingPathComponent(".kota/runs")
            if let entries = try? fm.contentsOfDirectory(
                at: candidate,
                includingPropertiesForKeys: [.contentModificationDateKey]
            ) {
                let latest = entries
                    .filter { $0.hasDirectoryPath }
                    .sorted { lhs, rhs in
                        let l = (try? lhs.resourceValues(forKeys: [.contentModificationDateKey])
                            .contentModificationDate) ?? .distantPast
                        let r = (try? rhs.resourceValues(forKeys: [.contentModificationDateKey])
                            .contentModificationDate) ?? .distantPast
                        return l > r
                    }
                    .first
                if let latest {
                    return latest.appendingPathComponent("rendered-trigger-workflow.txt")
                }
            }
            url = url.deletingLastPathComponent()
            if url.path == "/" { break }
        }
        return nil
    }
}

final class TriggerPayloadValidationTests: XCTestCase {
    func testEmptyTextValidatesAsEmpty() {
        XCTAssertEqual(validateTriggerPayload(""), .empty)
        XCTAssertEqual(validateTriggerPayload("   \n"), .empty)
    }

    func testValidJsonObjectReturnsObjectArm() {
        let text = #"{"taskId": "x", "n": 3}"#
        guard case .object(let data) = validateTriggerPayload(text) else {
            XCTFail("expected object arm")
            return
        }
        let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
        XCTAssertEqual(obj?["taskId"] as? String, "x")
    }

    func testJsonArrayIsRejected() {
        guard case .invalid(let message) = validateTriggerPayload("[1, 2]") else {
            XCTFail("expected invalid arm")
            return
        }
        XCTAssertTrue(message.contains("JSON object"), "got: \(message)")
    }

    func testMalformedJsonIsRejected() {
        guard case .invalid = validateTriggerPayload("{not json") else {
            XCTFail("expected invalid arm")
            return
        }
    }
}
