// Generated from scripts/daemon-contract-graph.mjs.
// Do not edit this file directly. Run `pnpm build:client-bindings`.

import type { DaemonTransport } from "#core/server/daemon-transport.js";
import type { AgentInspectResult, AgentsClient, AgentsListResult } from "#modules/agent-ops/client.js";
import type { AnswerClient, AnswerFilter, AnswerHistoryListFilter, AnswerHistoryListResult, AnswerHistoryShowFilter, AnswerHistoryShowResult, AnswerResult } from "#modules/answer/client.js";
import { decodeAnswerHistoryListResult, decodeAnswerHistoryShowResult } from "#modules/answer/client.js";
import type { ApprovalsClient } from "#modules/approval-queue/client.js";
import type { CaptureClient, CaptureFilter, CaptureResult } from "#modules/capture/client.js";
import type { ConfigClient } from "#modules/config/client.js";
import type { DaemonOpsClient, ScopesClient, SessionsClient, UiClient } from "#modules/daemon-ops/client.js";
import type { DoctorClient, DoctorFixResult, DoctorRunOptions, DoctorRunResult } from "#modules/doctor/client.js";
import type { EvalHarnessClient } from "#modules/eval-harness/client.js";
import type { AuditClient, AuditListFilter, AuditListResult } from "#modules/guardrails-audit/client.js";
import type { HarnessParityClient } from "#modules/harness-parity/client.js";
import type { HistoryClient } from "#modules/history/client.js";
import type { InboundSignalRouteListResult, InboundSignalRouteValidationResult, InboundSignalScopeSelection, InboundSignalsClient } from "#modules/inbound-signals/client.js";
import type { KnowledgeClient } from "#modules/knowledge/client.js";
import type { McpServerClient } from "#modules/mcp-server/client.js";
import type { MemoryClient } from "#modules/memory/client.js";
import type { ModuleInspectResult, ModuleReloadResult, ModulesAdminClient, ModulesClient, ModulesListResult } from "#modules/module-manager/client.js";
import type { OwnerDecisionsClient } from "#modules/owner-decisions/client.js";
import type { OwnerQuestionsClient } from "#modules/owner-questions/client.js";
import type { RecallClient, RecallFilter, RecallResult } from "#modules/recall/client.js";
import type { RepoTasksClient } from "#modules/repo-tasks/client.js";
import type { ResourceDiscoveryClient, ResourceDiscoveryFilter, ResourceDiscoveryResult } from "#modules/resource-discovery/client.js";
import type { RetractClient, RetractRequest, RetractResult } from "#modules/retract/client.js";
import type { SecretsClient } from "#modules/secrets/client.js";
import type { SetupClient } from "#modules/setup/client.js";
import type { SkillImportOptions, SkillImportResult, SkillsClient, SkillsListResult } from "#modules/skill-ops/client.js";
import type { VoiceClient } from "#modules/voice/client.js";
import type { WebClient } from "#modules/web/client.js";
import type { WebhookClient, WebhookListResult, WebhookSecretGenerateResult, WebhookSecretRemoveResult } from "#modules/webhook/client.js";
import type { WorkflowClient } from "#modules/workflow-ops/client.js";
import { parseCaptureResult, parseRetractResult } from "#root/client/daemon-contract.generated.js";

export interface KotaClient {
  forScope(scopeId: string): KotaClient;
  readonly workflow: WorkflowClient;
  readonly approvals: ApprovalsClient;
  readonly secrets: SecretsClient;
  readonly tasks: RepoTasksClient;
  readonly memory: MemoryClient;
  readonly ownerDecisions: OwnerDecisionsClient;
  readonly ownerQuestions: OwnerQuestionsClient;
  readonly history: HistoryClient;
  readonly inboundSignals: InboundSignalsClient;
  readonly knowledge: KnowledgeClient;
  readonly sessions: SessionsClient;
  readonly modules: ModulesClient;
  readonly agents: AgentsClient;
  readonly skills: SkillsClient;
  readonly harnessParity: HarnessParityClient;
  readonly webhook: WebhookClient;
  readonly voice: VoiceClient;
  readonly web: WebClient;
  readonly mcpServer: McpServerClient;
  readonly audit: AuditClient;
  readonly config: ConfigClient;
  readonly modulesAdmin: ModulesAdminClient;
  readonly daemonOps: DaemonOpsClient;
  readonly scopes: ScopesClient;
  readonly ui: UiClient;
  readonly doctor: DoctorClient;
  readonly evalHarness: EvalHarnessClient;
  readonly recall: RecallClient;
  readonly resourceDiscovery: ResourceDiscoveryClient;
  readonly answer: AnswerClient;
  readonly capture: CaptureClient;
  readonly retract: RetractClient;
  readonly setup: SetupClient;
}

export const KOTA_CLIENT_NAMESPACES = [
  "workflow",
  "approvals",
  "secrets",
  "tasks",
  "memory",
  "ownerDecisions",
  "ownerQuestions",
  "history",
  "inboundSignals",
  "knowledge",
  "sessions",
  "modules",
  "agents",
  "skills",
  "harnessParity",
  "webhook",
  "voice",
  "web",
  "mcpServer",
  "audit",
  "config",
  "modulesAdmin",
  "daemonOps",
  "scopes",
  "ui",
  "doctor",
  "evalHarness",
  "recall",
  "resourceDiscovery",
  "answer",
  "capture",
  "retract",
  "setup",
] as const satisfies ReadonlyArray<keyof KotaClient>;

export type KotaClientNamespace = (typeof KOTA_CLIENT_NAMESPACES)[number];
export type KotaClientPort<K extends KotaClientNamespace> = Readonly<Pick<KotaClient, K>>;
export type ScopedKotaClientPort<K extends KotaClientNamespace> = KotaClientPort<K> &
  Readonly<Pick<KotaClient, "forScope">>;
export type LocalClientHandlers = { [K in KotaClientNamespace]: KotaClient[K] };
export type DaemonClientHandlers = { [K in KotaClientNamespace]: KotaClient[K] };

function assignKotaClientNamespaces(
  target: object,
  handlers: LocalClientHandlers | DaemonClientHandlers,
): void {
  for (const name of KOTA_CLIENT_NAMESPACES) {
    Object.defineProperty(target, name, {
      configurable: false,
      enumerable: true,
      writable: false,
      value: handlers[name],
    });
  }
}

export abstract class KotaClientNamespaceHost implements KotaClient {
  abstract forScope(scopeId: string): KotaClient;
  declare readonly workflow: WorkflowClient;
  declare readonly approvals: ApprovalsClient;
  declare readonly secrets: SecretsClient;
  declare readonly tasks: RepoTasksClient;
  declare readonly memory: MemoryClient;
  declare readonly ownerDecisions: OwnerDecisionsClient;
  declare readonly ownerQuestions: OwnerQuestionsClient;
  declare readonly history: HistoryClient;
  declare readonly inboundSignals: InboundSignalsClient;
  declare readonly knowledge: KnowledgeClient;
  declare readonly sessions: SessionsClient;
  declare readonly modules: ModulesClient;
  declare readonly agents: AgentsClient;
  declare readonly skills: SkillsClient;
  declare readonly harnessParity: HarnessParityClient;
  declare readonly webhook: WebhookClient;
  declare readonly voice: VoiceClient;
  declare readonly web: WebClient;
  declare readonly mcpServer: McpServerClient;
  declare readonly audit: AuditClient;
  declare readonly config: ConfigClient;
  declare readonly modulesAdmin: ModulesAdminClient;
  declare readonly daemonOps: DaemonOpsClient;
  declare readonly scopes: ScopesClient;
  declare readonly ui: UiClient;
  declare readonly doctor: DoctorClient;
  declare readonly evalHarness: EvalHarnessClient;
  declare readonly recall: RecallClient;
  declare readonly resourceDiscovery: ResourceDiscoveryClient;
  declare readonly answer: AnswerClient;
  declare readonly capture: CaptureClient;
  declare readonly retract: RetractClient;
  declare readonly setup: SetupClient;

  constructor(handlers: LocalClientHandlers | DaemonClientHandlers) {
    assignKotaClientNamespaces(this, handlers);
  }
}

export class KotaClientScopeError extends Error {
  readonly reason = "unknown_scope" as const;
  readonly scopeId: string;

  constructor(scopeId: string, cause?: Error) {
    super(`Unknown scope: ${scopeId}`, cause ? { cause } : undefined);
    this.name = "KotaClientScopeError";
    this.scopeId = scopeId;
  }
}

// ---------------------------------------------------------------------------
// Routine Daemon Client Implementations
// Generated from canonical operation descriptor authority.
// ---------------------------------------------------------------------------

class RoutineAgentsClient implements AgentsClient {
  constructor(private readonly transport: DaemonTransport) {}

  async list(): Promise<AgentsListResult> {
    return this.transport.requestStrict<AgentsListResult>("GET", "/agents");
  }

  async inspect(name: string): Promise<AgentInspectResult> {
    return this.transport.requestStrict<AgentInspectResult>(
      "GET",
      `/agents/${encodeURIComponent(name)}`,
    );
  }
}

class RoutineSkillsClient implements SkillsClient {
  constructor(private readonly transport: DaemonTransport) {}

  async list(): Promise<SkillsListResult> {
    return this.transport.requestStrict<SkillsListResult>("GET", "/skills");
  }

  async import(
    source: string,
    options?: SkillImportOptions,
  ): Promise<SkillImportResult> {
    return this.transport.requestStrict<SkillImportResult>(
      "POST",
      "/skills/import",
      {
        source,
        ...(options?.name !== undefined && { name: options.name }),
        ...(options?.skill !== undefined && { skill: options.skill }),
        ...(options?.all !== undefined && { all: options.all }),
      },
    );
  }
}

class RoutineRecallClient implements RecallClient {
  constructor(private readonly transport: DaemonTransport) {}

  async recall(query: string, filter?: RecallFilter): Promise<RecallResult> {
    return this.transport.requestStrict<RecallResult>("POST", "/recall", {
      query,
      ...(filter && { filter }),
    });
  }
}

class RoutineCaptureClient implements CaptureClient {
  constructor(private readonly transport: DaemonTransport) {}

  async capture(text: string, filter?: CaptureFilter): Promise<CaptureResult> {
    const decoded = await this.transport.requestStrict<unknown>("POST", "/capture", {
      text,
      ...(filter && { filter }),
    });
    return parseCaptureResult(decoded);
  }
}

class RoutineRetractClient implements RetractClient {
  constructor(private readonly transport: DaemonTransport) {}

  async retract(request: RetractRequest): Promise<RetractResult> {
    const decoded = await this.transport.requestStrict<unknown>(
      "POST",
      "/retract",
      request,
    );
    return parseRetractResult(decoded);
  }
}

class RoutineResourceDiscoveryClient implements ResourceDiscoveryClient {
  constructor(private readonly transport: DaemonTransport) {}

  async discover(
    query: string,
    filter?: ResourceDiscoveryFilter,
  ): Promise<ResourceDiscoveryResult> {
    return this.transport.requestStrict<ResourceDiscoveryResult>(
      "POST",
      "/resource-discovery",
      {
        query,
        ...(filter ? { filter } : {}),
      },
    );
  }
}

class RoutineDoctorClient implements DoctorClient {
  constructor(private readonly transport: DaemonTransport) {}

  async run(options?: DoctorRunOptions): Promise<DoctorRunResult> {
    const params = new URLSearchParams();
    if (options?.skipConnectivity) params.set("skipConnectivity", "true");
    if (options?.preset) params.set("preset", options.preset);
    const query = params.toString() ? `?${params.toString()}` : "";
    return this.transport.requestStrict<DoctorRunResult>(
      "GET",
      `/doctor/run${query}`,
    );
  }

  async fix(): Promise<DoctorFixResult> {
    return this.transport.requestStrict<DoctorFixResult>("POST", "/doctor/fix");
  }
}

class RoutineAuditClient implements AuditClient {
  constructor(private readonly transport: DaemonTransport) {}

  async list(filter?: AuditListFilter): Promise<AuditListResult> {
    const params = new URLSearchParams();
    if (filter?.limit !== undefined) params.set("limit", String(filter.limit));
    if (filter?.since) params.set("since", filter.since);
    if (filter?.tool) params.set("tool", filter.tool);
    if (filter?.risk) params.set("risk", filter.risk);
    if (filter?.policy) params.set("policy", filter.policy);
    if (filter?.session) params.set("session", filter.session);
    const query = params.toString() ? `?${params.toString()}` : "";
    return this.transport.requestStrict<AuditListResult>("GET", `/audit${query}`);
  }
}

class RoutineWebhookClient implements WebhookClient {
  constructor(private readonly transport: DaemonTransport) {}

  async list(): Promise<WebhookListResult> {
    return this.transport.requestStrict<WebhookListResult>("GET", "/webhooks");
  }

  async secretGenerate(
    workflow: string,
  ): Promise<WebhookSecretGenerateResult> {
    return this.transport.requestStrict<WebhookSecretGenerateResult>(
      "POST",
      `/webhooks/${encodeURIComponent(workflow)}/secret`,
    );
  }

  async secretRemove(workflow: string): Promise<WebhookSecretRemoveResult> {
    return this.transport.requestStrict<WebhookSecretRemoveResult>(
      "DELETE",
      `/webhooks/${encodeURIComponent(workflow)}/secret`,
    );
  }
}

class RoutineModulesClient implements ModulesClient {
  constructor(private readonly transport: DaemonTransport) {}

  async list(): Promise<ModulesListResult> {
    return this.transport.requestStrict<ModulesListResult>("GET", "/modules");
  }
}

class RoutineModulesAdminClient implements ModulesAdminClient {
  constructor(private readonly transport: DaemonTransport) {}

  async inspect(name: string): Promise<ModuleInspectResult> {
    return this.transport.requestStrict<ModuleInspectResult>(
      "GET",
      `/modules/${encodeURIComponent(name)}`,
    );
  }

  async reload(name: string): Promise<ModuleReloadResult> {
    return this.transport.requestStrict<ModuleReloadResult>(
      "POST",
      `/modules/${encodeURIComponent(name)}/reload`,
    );
  }
}

class RoutineInboundSignalsClient implements InboundSignalsClient {
  constructor(private readonly transport: DaemonTransport) {}

  async listRoutes(
    scopeSelector?: InboundSignalScopeSelection,
  ): Promise<InboundSignalRouteListResult> {
    const query = scopeSelector?.scopeId
      ? `?scopeId=${encodeURIComponent(scopeSelector.scopeId)}`
      : "";
    const result = await this.transport.request<InboundSignalRouteListResult>(
      "GET",
      `/inbound-signals/routes${query}`,
    );
    if (!result) {
      throw new Error("Daemon unreachable while listing inbound signal routes");
    }
    return result;
  }

  async validateRoutes(
    scopeSelector?: InboundSignalScopeSelection,
  ): Promise<InboundSignalRouteValidationResult> {
    return (await this.listRoutes(scopeSelector)).validation;
  }
}

class RoutineAnswerClient implements AnswerClient {
  constructor(private readonly transport: DaemonTransport) {}

  async answer(query: string, filter?: AnswerFilter): Promise<AnswerResult> {
    return this.transport.requestStrict<AnswerResult>("POST", "/answer", {
      query,
      ...(filter && { filter }),
    });
  }

  async log(filter?: AnswerHistoryListFilter): Promise<AnswerHistoryListResult> {
    const params = new URLSearchParams();
    if (filter?.limit !== undefined) params.set("limit", String(filter.limit));
    if (filter?.beforeId !== undefined) params.set("beforeId", filter.beforeId);
    if (filter?.scopeId !== undefined) params.set("scopeId", filter.scopeId);
    const query = params.toString() ? `?${params.toString()}` : "";
    const decoded = await this.transport.requestStrict<unknown>(
      "GET",
      `/answers${query}`,
    );
    return decodeAnswerHistoryListResult(decoded);
  }

  async show(
    id: string,
    scope?: AnswerHistoryShowFilter,
  ): Promise<AnswerHistoryShowResult> {
    const params = new URLSearchParams();
    if (scope?.scopeId !== undefined) params.set("scopeId", scope.scopeId);
    const query = params.toString() ? `?${params.toString()}` : "";
    const decoded = await this.transport.requestStrict<unknown>(
      "GET",
      `/answers/${encodeURIComponent(id)}${query}`,
    );
    return decodeAnswerHistoryShowResult(decoded);
  }
}

export type RoutineDaemonClientHandlers = Pick<
  DaemonClientHandlers,
  | "agents"
  | "skills"
  | "recall"
  | "capture"
  | "retract"
  | "resourceDiscovery"
  | "doctor"
  | "audit"
  | "webhook"
  | "modules"
  | "modulesAdmin"
  | "inboundSignals"
  | "answer"
>;

export function createRoutineDaemonClientHandlers(
  transport: DaemonTransport,
): RoutineDaemonClientHandlers {
  return {
    agents: new RoutineAgentsClient(transport),
    skills: new RoutineSkillsClient(transport),
    recall: new RoutineRecallClient(transport),
    capture: new RoutineCaptureClient(transport),
    retract: new RoutineRetractClient(transport),
    resourceDiscovery: new RoutineResourceDiscoveryClient(transport),
    doctor: new RoutineDoctorClient(transport),
    audit: new RoutineAuditClient(transport),
    webhook: new RoutineWebhookClient(transport),
    modules: new RoutineModulesClient(transport),
    modulesAdmin: new RoutineModulesAdminClient(transport),
    inboundSignals: new RoutineInboundSignalsClient(transport),
    answer: new RoutineAnswerClient(transport),
  };
}
