// Generated from scripts/daemon-contract-graph.mjs.
// Do not edit this file directly. Run `pnpm build:client-bindings`.

import type { AgentsClient } from "#modules/agent-ops/client.js";
import type { AnswerClient } from "#modules/answer/client.js";
import type { ApprovalsClient } from "#modules/approval-queue/client.js";
import type { CaptureClient } from "#modules/capture/client.js";
import type { ConfigClient } from "#modules/config/client.js";
import type { DaemonOpsClient, ScopesClient, SessionsClient, UiClient } from "#modules/daemon-ops/client.js";
import type { DoctorClient } from "#modules/doctor/client.js";
import type { EvalHarnessClient } from "#modules/eval-harness/client.js";
import type { AuditClient } from "#modules/guardrails-audit/client.js";
import type { HarnessParityClient } from "#modules/harness-parity/client.js";
import type { HistoryClient } from "#modules/history/client.js";
import type { InboundSignalsClient } from "#modules/inbound-signals/client.js";
import type { KnowledgeClient } from "#modules/knowledge/client.js";
import type { McpServerClient } from "#modules/mcp-server/client.js";
import type { MemoryClient } from "#modules/memory/client.js";
import type { ModulesAdminClient, ModulesClient } from "#modules/module-manager/client.js";
import type { OwnerDecisionsClient } from "#modules/owner-decisions/client.js";
import type { OwnerQuestionsClient } from "#modules/owner-questions/client.js";
import type { RecallClient } from "#modules/recall/client.js";
import type { RepoTasksClient } from "#modules/repo-tasks/client.js";
import type { ResourceDiscoveryClient } from "#modules/resource-discovery/client.js";
import type { RetractClient } from "#modules/retract/client.js";
import type { SecretsClient } from "#modules/secrets/client.js";
import type { SetupClient } from "#modules/setup/client.js";
import type { SkillsClient } from "#modules/skill-ops/client.js";
import type { VoiceClient } from "#modules/voice/client.js";
import type { WebClient } from "#modules/web/client.js";
import type { WebhookClient } from "#modules/webhook/client.js";
import type { WorkflowClient } from "#modules/workflow-ops/client.js";

export interface KotaClient {
  forScope(scopeId: string): KotaClient;
  readonly workflow: WorkflowClient;
  readonly approvals: ApprovalsClient;
  readonly secrets: SecretsClient;
  readonly tasks: RepoTasksClient;
  readonly memory: MemoryClient;
  readonly ownerDecisions: OwnerDecisionsClient;
  readonly ownerQuestions: OwnerQuestionsClient;
  readonly history: HistoryClient;
  readonly inboundSignals: InboundSignalsClient;
  readonly knowledge: KnowledgeClient;
  readonly sessions: SessionsClient;
  readonly modules: ModulesClient;
  readonly agents: AgentsClient;
  readonly skills: SkillsClient;
  readonly harnessParity: HarnessParityClient;
  readonly webhook: WebhookClient;
  readonly voice: VoiceClient;
  readonly web: WebClient;
  readonly mcpServer: McpServerClient;
  readonly audit: AuditClient;
  readonly config: ConfigClient;
  readonly modulesAdmin: ModulesAdminClient;
  readonly daemonOps: DaemonOpsClient;
  readonly scopes: ScopesClient;
  readonly ui: UiClient;
  readonly doctor: DoctorClient;
  readonly evalHarness: EvalHarnessClient;
  readonly recall: RecallClient;
  readonly resourceDiscovery: ResourceDiscoveryClient;
  readonly answer: AnswerClient;
  readonly capture: CaptureClient;
  readonly retract: RetractClient;
  readonly setup: SetupClient;
}

export const KOTA_CLIENT_NAMESPACES = [
  "workflow",
  "approvals",
  "secrets",
  "tasks",
  "memory",
  "ownerDecisions",
  "ownerQuestions",
  "history",
  "inboundSignals",
  "knowledge",
  "sessions",
  "modules",
  "agents",
  "skills",
  "harnessParity",
  "webhook",
  "voice",
  "web",
  "mcpServer",
  "audit",
  "config",
  "modulesAdmin",
  "daemonOps",
  "scopes",
  "ui",
  "doctor",
  "evalHarness",
  "recall",
  "resourceDiscovery",
  "answer",
  "capture",
  "retract",
  "setup",
] as const satisfies ReadonlyArray<keyof KotaClient>;

export type KotaClientNamespace = (typeof KOTA_CLIENT_NAMESPACES)[number];
export type KotaClientPort<K extends KotaClientNamespace> = Readonly<Pick<KotaClient, K>>;
export type ScopedKotaClientPort<K extends KotaClientNamespace> = KotaClientPort<K> &
  Readonly<Pick<KotaClient, "forScope">>;
export type LocalClientHandlers = { [K in KotaClientNamespace]: KotaClient[K] };
export type DaemonClientHandlers = { [K in KotaClientNamespace]: KotaClient[K] };

function assignKotaClientNamespaces(
  target: object,
  handlers: LocalClientHandlers | DaemonClientHandlers,
): void {
  for (const name of KOTA_CLIENT_NAMESPACES) {
    Object.defineProperty(target, name, {
      configurable: false,
      enumerable: true,
      writable: false,
      value: handlers[name],
    });
  }
}

export abstract class KotaClientNamespaceHost implements KotaClient {
  abstract forScope(scopeId: string): KotaClient;
  declare readonly workflow: WorkflowClient;
  declare readonly approvals: ApprovalsClient;
  declare readonly secrets: SecretsClient;
  declare readonly tasks: RepoTasksClient;
  declare readonly memory: MemoryClient;
  declare readonly ownerDecisions: OwnerDecisionsClient;
  declare readonly ownerQuestions: OwnerQuestionsClient;
  declare readonly history: HistoryClient;
  declare readonly inboundSignals: InboundSignalsClient;
  declare readonly knowledge: KnowledgeClient;
  declare readonly sessions: SessionsClient;
  declare readonly modules: ModulesClient;
  declare readonly agents: AgentsClient;
  declare readonly skills: SkillsClient;
  declare readonly harnessParity: HarnessParityClient;
  declare readonly webhook: WebhookClient;
  declare readonly voice: VoiceClient;
  declare readonly web: WebClient;
  declare readonly mcpServer: McpServerClient;
  declare readonly audit: AuditClient;
  declare readonly config: ConfigClient;
  declare readonly modulesAdmin: ModulesAdminClient;
  declare readonly daemonOps: DaemonOpsClient;
  declare readonly scopes: ScopesClient;
  declare readonly ui: UiClient;
  declare readonly doctor: DoctorClient;
  declare readonly evalHarness: EvalHarnessClient;
  declare readonly recall: RecallClient;
  declare readonly resourceDiscovery: ResourceDiscoveryClient;
  declare readonly answer: AnswerClient;
  declare readonly capture: CaptureClient;
  declare readonly retract: RetractClient;
  declare readonly setup: SetupClient;

  constructor(handlers: LocalClientHandlers | DaemonClientHandlers) {
    assignKotaClientNamespaces(this, handlers);
  }
}

export class KotaClientScopeError extends Error {
  readonly reason = "unknown_scope" as const;
  readonly scopeId: string;

  constructor(scopeId: string, cause?: Error) {
    super(`Unknown scope: ${scopeId}`, cause ? { cause } : undefined);
    this.name = "KotaClientScopeError";
    this.scopeId = scopeId;
  }
}
