// Generated from scripts/daemon-contract-graph.mjs.
// Do not edit this file directly. Run `pnpm build:client-bindings`.

import type { DaemonTransport } from "#core/server/daemon-transport.js";
import type { AgentsClient } from "#modules/agent-ops/client.js";
import type { AnswerClient } from "#modules/answer/client.js";
import { decodeAnswerHistoryListResult, decodeAnswerHistoryShowResult } from "#modules/answer/client.js";
import type { ApprovalsClient } from "#modules/approval-queue/client.js";
import type { CaptureClient } from "#modules/capture/client.js";
import type { ConfigClient } from "#modules/config/client.js";
import type { DaemonOpsClient, ScopesClient, SessionsClient, UiClient } from "#modules/daemon-ops/client.js";
import type { DoctorClient } from "#modules/doctor/client.js";
import type { EvalHarnessClient } from "#modules/eval-harness/client.js";
import type { AuditClient } from "#modules/guardrails-audit/client.js";
import type { HarnessParityClient } from "#modules/harness-parity/client.js";
import type { HistoryClient } from "#modules/history/client.js";
import type { InboundSignalsClient } from "#modules/inbound-signals/client.js";
import type { KnowledgeClient } from "#modules/knowledge/client.js";
import type { McpServerClient } from "#modules/mcp-server/client.js";
import type { MemoryClient } from "#modules/memory/client.js";
import type { ModulesAdminClient, ModulesClient } from "#modules/module-manager/client.js";
import type { OwnerDecisionsClient } from "#modules/owner-decisions/client.js";
import type { OwnerQuestionsClient } from "#modules/owner-questions/client.js";
import type { RecallClient } from "#modules/recall/client.js";
import type { RepoTasksClient } from "#modules/repo-tasks/client.js";
import type { ResourceDiscoveryClient } from "#modules/resource-discovery/client.js";
import type { RetractClient } from "#modules/retract/client.js";
import type { SecretsClient } from "#modules/secrets/client.js";
import type { SetupClient } from "#modules/setup/client.js";
import type { SkillsClient } from "#modules/skill-ops/client.js";
import type { VoiceClient } from "#modules/voice/client.js";
import type { WebClient } from "#modules/web/client.js";
import type { WebhookClient } from "#modules/webhook/client.js";
import type { WorkflowClient } from "#modules/workflow-ops/client.js";
import { parseCaptureResult, parseHistorySearchResponse, parseKnowledgeSearchResponse, parseMemorySearchResponse, parseRetractResult, parseTasksSearchResponse } from "#root/client/daemon-contract.generated.js";

export interface KotaClient {
  forScope(scopeId: string): KotaClient;
  readonly workflow: WorkflowClient;
  readonly approvals: ApprovalsClient;
  readonly secrets: SecretsClient;
  readonly tasks: RepoTasksClient;
  readonly memory: MemoryClient;
  readonly ownerDecisions: OwnerDecisionsClient;
  readonly ownerQuestions: OwnerQuestionsClient;
  readonly history: HistoryClient;
  readonly inboundSignals: InboundSignalsClient;
  readonly knowledge: KnowledgeClient;
  readonly sessions: SessionsClient;
  readonly modules: ModulesClient;
  readonly agents: AgentsClient;
  readonly skills: SkillsClient;
  readonly harnessParity: HarnessParityClient;
  readonly webhook: WebhookClient;
  readonly voice: VoiceClient;
  readonly web: WebClient;
  readonly mcpServer: McpServerClient;
  readonly audit: AuditClient;
  readonly config: ConfigClient;
  readonly modulesAdmin: ModulesAdminClient;
  readonly daemonOps: DaemonOpsClient;
  readonly scopes: ScopesClient;
  readonly ui: UiClient;
  readonly doctor: DoctorClient;
  readonly evalHarness: EvalHarnessClient;
  readonly recall: RecallClient;
  readonly resourceDiscovery: ResourceDiscoveryClient;
  readonly answer: AnswerClient;
  readonly capture: CaptureClient;
  readonly retract: RetractClient;
  readonly setup: SetupClient;
}

export const KOTA_CLIENT_NAMESPACES = [
  "workflow",
  "approvals",
  "secrets",
  "tasks",
  "memory",
  "ownerDecisions",
  "ownerQuestions",
  "history",
  "inboundSignals",
  "knowledge",
  "sessions",
  "modules",
  "agents",
  "skills",
  "harnessParity",
  "webhook",
  "voice",
  "web",
  "mcpServer",
  "audit",
  "config",
  "modulesAdmin",
  "daemonOps",
  "scopes",
  "ui",
  "doctor",
  "evalHarness",
  "recall",
  "resourceDiscovery",
  "answer",
  "capture",
  "retract",
  "setup",
] as const satisfies ReadonlyArray<keyof KotaClient>;

export type KotaClientNamespace = (typeof KOTA_CLIENT_NAMESPACES)[number];
export type KotaClientPort<K extends KotaClientNamespace> = Readonly<Pick<KotaClient, K>>;
export type ScopedKotaClientPort<K extends KotaClientNamespace> = KotaClientPort<K> &
  Readonly<Pick<KotaClient, "forScope">>;
export type LocalClientHandlers = { [K in KotaClientNamespace]: KotaClient[K] };
export type DaemonClientHandlers = { [K in KotaClientNamespace]: KotaClient[K] };

function assignKotaClientNamespaces(
  target: object,
  handlers: LocalClientHandlers | DaemonClientHandlers,
): void {
  for (const name of KOTA_CLIENT_NAMESPACES) {
    Object.defineProperty(target, name, {
      configurable: false,
      enumerable: true,
      writable: false,
      value: handlers[name],
    });
  }
}

export abstract class KotaClientNamespaceHost implements KotaClient {
  abstract forScope(scopeId: string): KotaClient;
  declare readonly workflow: WorkflowClient;
  declare readonly approvals: ApprovalsClient;
  declare readonly secrets: SecretsClient;
  declare readonly tasks: RepoTasksClient;
  declare readonly memory: MemoryClient;
  declare readonly ownerDecisions: OwnerDecisionsClient;
  declare readonly ownerQuestions: OwnerQuestionsClient;
  declare readonly history: HistoryClient;
  declare readonly inboundSignals: InboundSignalsClient;
  declare readonly knowledge: KnowledgeClient;
  declare readonly sessions: SessionsClient;
  declare readonly modules: ModulesClient;
  declare readonly agents: AgentsClient;
  declare readonly skills: SkillsClient;
  declare readonly harnessParity: HarnessParityClient;
  declare readonly webhook: WebhookClient;
  declare readonly voice: VoiceClient;
  declare readonly web: WebClient;
  declare readonly mcpServer: McpServerClient;
  declare readonly audit: AuditClient;
  declare readonly config: ConfigClient;
  declare readonly modulesAdmin: ModulesAdminClient;
  declare readonly daemonOps: DaemonOpsClient;
  declare readonly scopes: ScopesClient;
  declare readonly ui: UiClient;
  declare readonly doctor: DoctorClient;
  declare readonly evalHarness: EvalHarnessClient;
  declare readonly recall: RecallClient;
  declare readonly resourceDiscovery: ResourceDiscoveryClient;
  declare readonly answer: AnswerClient;
  declare readonly capture: CaptureClient;
  declare readonly retract: RetractClient;
  declare readonly setup: SetupClient;

  constructor(handlers: LocalClientHandlers | DaemonClientHandlers) {
    assignKotaClientNamespaces(this, handlers);
  }
}

export class KotaClientScopeError extends Error {
  readonly reason = "unknown_scope" as const;
  readonly scopeId: string;

  constructor(scopeId: string, cause?: Error) {
    super(`Unknown scope: ${scopeId}`, cause ? { cause } : undefined);
    this.name = "KotaClientScopeError";
    this.scopeId = scopeId;
  }
}

function appendQueryValue(
  params: URLSearchParams,
  name: string,
  value: unknown,
): void {
  if (value === undefined) return;
  if (Array.isArray(value)) {
    for (const item of value) appendQueryValue(params, name, item);
    return;
  }
  params.append(name, String(value));
}

function appendQueryObject(
  params: URLSearchParams,
  value: object | undefined,
  wireNames: Readonly<Record<string, string>> = {},
): void {
  if (!value) return;
  for (const [name, item] of Object.entries(value)) {
    appendQueryValue(params, wireNames[name] ?? name, item);
  }
}

function withQuery(path: string, params: URLSearchParams): string {
  const query = params.toString();
  return query.length > 0 ? `${path}?${query}` : path;
}

function omitBodyKeys(
  value: object | undefined,
  omitted: readonly string[],
): Record<string, unknown> | undefined {
  if (!value) return undefined;
  return Object.fromEntries(
    Object.entries(value).filter(([name]) => !omitted.includes(name)),
  );
}

class RoutineAgentsClient implements AgentsClient {
  constructor(private readonly transport: DaemonTransport) {}

  async list(): Promise<Awaited<ReturnType<AgentsClient["list"]>>> {
    return this.transport.requestStrict<Awaited<ReturnType<AgentsClient["list"]>>>("GET", "/agents");
  }

  async inspect(...[name]: Parameters<AgentsClient["inspect"]>): Promise<Awaited<ReturnType<AgentsClient["inspect"]>>> {
    return this.transport.requestStrict<Awaited<ReturnType<AgentsClient["inspect"]>>>("GET", `/agents/${encodeURIComponent(name)}`);
  }
}

class RoutineSkillsClient implements SkillsClient {
  constructor(private readonly transport: DaemonTransport) {}

  async list(): Promise<Awaited<ReturnType<SkillsClient["list"]>>> {
    return this.transport.requestStrict<Awaited<ReturnType<SkillsClient["list"]>>>("GET", "/skills");
  }

  async import(...[source, options]: Parameters<SkillsClient["import"]>): Promise<Awaited<ReturnType<SkillsClient["import"]>>> {
    return this.transport.requestStrict<Awaited<ReturnType<SkillsClient["import"]>>>("POST", "/skills/import", { source: source, ...(options ?? {}) });
  }
}

class RoutineRecallClient implements RecallClient {
  constructor(private readonly transport: DaemonTransport) {}

  async recall(...[query, filter]: Parameters<RecallClient["recall"]>): Promise<Awaited<ReturnType<RecallClient["recall"]>>> {
    return this.transport.requestStrict<Awaited<ReturnType<RecallClient["recall"]>>>("POST", "/recall", { query: query, ...(filter !== undefined && { filter: filter }) });
  }
}

class RoutineCaptureClient implements CaptureClient {
  constructor(private readonly transport: DaemonTransport) {}

  async capture(...[text, filter]: Parameters<CaptureClient["capture"]>): Promise<Awaited<ReturnType<CaptureClient["capture"]>>> {
    const decoded = await this.transport.requestStrict<unknown>("POST", "/capture", { text: text, ...(filter !== undefined && { filter: filter }) });
    return parseCaptureResult(decoded);
  }
}

class RoutineRetractClient implements RetractClient {
  constructor(private readonly transport: DaemonTransport) {}

  async retract(...[request]: Parameters<RetractClient["retract"]>): Promise<Awaited<ReturnType<RetractClient["retract"]>>> {
    const decoded = await this.transport.requestStrict<unknown>("POST", "/retract", request);
    return parseRetractResult(decoded);
  }
}

class RoutineResourceDiscoveryClient implements ResourceDiscoveryClient {
  constructor(private readonly transport: DaemonTransport) {}

  async discover(...[query, filter]: Parameters<ResourceDiscoveryClient["discover"]>): Promise<Awaited<ReturnType<ResourceDiscoveryClient["discover"]>>> {
    return this.transport.requestStrict<Awaited<ReturnType<ResourceDiscoveryClient["discover"]>>>("POST", "/resource-discovery", { query: query, ...(filter !== undefined && { filter: filter }) });
  }
}

class RoutineDoctorClient implements DoctorClient {
  constructor(private readonly transport: DaemonTransport) {}

  async run(...[options]: Parameters<DoctorClient["run"]>): Promise<Awaited<ReturnType<DoctorClient["run"]>>> {
    const params = new URLSearchParams();
    appendQueryObject(params, options);
    return this.transport.requestStrict<Awaited<ReturnType<DoctorClient["run"]>>>("GET", withQuery("/doctor/run", params));
  }

  async fix(): Promise<Awaited<ReturnType<DoctorClient["fix"]>>> {
    return this.transport.requestStrict<Awaited<ReturnType<DoctorClient["fix"]>>>("POST", "/doctor/fix");
  }
}

class RoutineAuditClient implements AuditClient {
  constructor(private readonly transport: DaemonTransport) {}

  async list(...[filter]: Parameters<AuditClient["list"]>): Promise<Awaited<ReturnType<AuditClient["list"]>>> {
    const params = new URLSearchParams();
    appendQueryObject(params, filter);
    return this.transport.requestStrict<Awaited<ReturnType<AuditClient["list"]>>>("GET", withQuery("/audit", params));
  }
}

class RoutineWebhookClient implements WebhookClient {
  constructor(private readonly transport: DaemonTransport) {}

  async list(): Promise<Awaited<ReturnType<WebhookClient["list"]>>> {
    return this.transport.requestStrict<Awaited<ReturnType<WebhookClient["list"]>>>("GET", "/webhooks");
  }

  async secretGenerate(...[workflow]: Parameters<WebhookClient["secretGenerate"]>): Promise<Awaited<ReturnType<WebhookClient["secretGenerate"]>>> {
    return this.transport.requestStrict<Awaited<ReturnType<WebhookClient["secretGenerate"]>>>("POST", `/webhooks/${encodeURIComponent(workflow)}/secret`);
  }

  async secretRemove(...[workflow]: Parameters<WebhookClient["secretRemove"]>): Promise<Awaited<ReturnType<WebhookClient["secretRemove"]>>> {
    return this.transport.requestStrict<Awaited<ReturnType<WebhookClient["secretRemove"]>>>("DELETE", `/webhooks/${encodeURIComponent(workflow)}/secret`);
  }
}

class RoutineModulesClient implements ModulesClient {
  constructor(private readonly transport: DaemonTransport) {}

  async list(): Promise<Awaited<ReturnType<ModulesClient["list"]>>> {
    return this.transport.requestStrict<Awaited<ReturnType<ModulesClient["list"]>>>("GET", "/modules");
  }
}

class RoutineModulesAdminClient implements ModulesAdminClient {
  constructor(private readonly transport: DaemonTransport) {}

  async inspect(...[name]: Parameters<ModulesAdminClient["inspect"]>): Promise<Awaited<ReturnType<ModulesAdminClient["inspect"]>>> {
    return this.transport.requestStrict<Awaited<ReturnType<ModulesAdminClient["inspect"]>>>("GET", `/modules/${encodeURIComponent(name)}`);
  }

  async reload(...[name]: Parameters<ModulesAdminClient["reload"]>): Promise<Awaited<ReturnType<ModulesAdminClient["reload"]>>> {
    return this.transport.requestStrict<Awaited<ReturnType<ModulesAdminClient["reload"]>>>("POST", `/modules/${encodeURIComponent(name)}/reload`);
  }
}

class RoutineInboundSignalsClient implements InboundSignalsClient {
  constructor(private readonly transport: DaemonTransport) {}

  async listRoutes(...[scopeSelector]: Parameters<InboundSignalsClient["listRoutes"]>): Promise<Awaited<ReturnType<InboundSignalsClient["listRoutes"]>>> {
    const params = new URLSearchParams();
    appendQueryValue(params, "scopeId", scopeSelector?.scopeId);
    const result = await this.transport.request<Awaited<ReturnType<InboundSignalsClient["listRoutes"]>>>("GET", withQuery("/inbound-signals/routes", params));
    if (!result) {
      throw new Error("Daemon unreachable while listing inbound signal routes");
    }
    return result;
  }

  async validateRoutes(...[scopeSelector]: Parameters<InboundSignalsClient["validateRoutes"]>): Promise<Awaited<ReturnType<InboundSignalsClient["validateRoutes"]>>> {
    return (await this.listRoutes(scopeSelector)).validation;
  }
}

class RoutineAnswerClient implements AnswerClient {
  constructor(private readonly transport: DaemonTransport) {}

  async answer(...[query, filter]: Parameters<AnswerClient["answer"]>): Promise<Awaited<ReturnType<AnswerClient["answer"]>>> {
    return this.transport.requestStrict<Awaited<ReturnType<AnswerClient["answer"]>>>("POST", "/answer", { query: query, ...(filter !== undefined && { filter: filter }) });
  }

  async log(...[filter]: Parameters<AnswerClient["log"]>): Promise<Awaited<ReturnType<AnswerClient["log"]>>> {
    const params = new URLSearchParams();
    appendQueryObject(params, filter);
    const decoded = await this.transport.requestStrict<unknown>("GET", withQuery("/answers", params));
    return decodeAnswerHistoryListResult(decoded);
  }

  async show(...[id, scope]: Parameters<AnswerClient["show"]>): Promise<Awaited<ReturnType<AnswerClient["show"]>>> {
    const params = new URLSearchParams();
    appendQueryObject(params, scope);
    const decoded = await this.transport.requestStrict<unknown>("GET", withQuery(`/answers/${encodeURIComponent(id)}`, params));
    return decodeAnswerHistoryShowResult(decoded);
  }
}

export type MemoryDaemonClientExceptions = Pick<
  MemoryClient,
  "delete"
>;

export function createMemoryDaemonClient(
  transport: DaemonTransport,
  exceptions: MemoryDaemonClientExceptions,
): MemoryClient {
  return {
    async list(...[filter]: Parameters<MemoryClient["list"]>): Promise<Awaited<ReturnType<MemoryClient["list"]>>> {
      const params = new URLSearchParams();
      appendQueryObject(params, filter);
      return transport.requestStrict<Awaited<ReturnType<MemoryClient["list"]>>>("GET", withQuery("/api/memory", params));
    },
    async add(...[content, tags, scope]: Parameters<MemoryClient["add"]>): Promise<Awaited<ReturnType<MemoryClient["add"]>>> {
      const params = new URLSearchParams();
      appendQueryValue(params, "scopeId", scope?.scopeId);
      return transport.requestStrict<Awaited<ReturnType<MemoryClient["add"]>>>("POST", withQuery("/api/memory", params), { content: content, tags: tags ?? [] });
    },
    async search(...[query, filter]: Parameters<MemoryClient["search"]>): Promise<Awaited<ReturnType<MemoryClient["search"]>>> {
      const params = new URLSearchParams();
      appendQueryValue(params, "q", query);
      appendQueryObject(params, filter);
      const decoded = await transport.requestStrict<unknown>("GET", withQuery("/api/memory/search", params));
      return parseMemorySearchResponse(decoded);
    },
    async reindex(...[scope]: Parameters<MemoryClient["reindex"]>): Promise<Awaited<ReturnType<MemoryClient["reindex"]>>> {
      const params = new URLSearchParams();
      appendQueryValue(params, "scopeId", scope?.scopeId);
      return transport.requestStrict<Awaited<ReturnType<MemoryClient["reindex"]>>>("POST", withQuery("/api/memory/reindex", params));
    },
    ...exceptions,
  };
}

export type KnowledgeDaemonClientExceptions = Pick<
  KnowledgeClient,
  "show" | "delete"
>;

export function createKnowledgeDaemonClient(
  transport: DaemonTransport,
  exceptions: KnowledgeDaemonClientExceptions,
): KnowledgeClient {
  return {
    async list(...[filter]: Parameters<KnowledgeClient["list"]>): Promise<Awaited<ReturnType<KnowledgeClient["list"]>>> {
      const params = new URLSearchParams();
      appendQueryObject(params, filter);
      return transport.requestStrict<Awaited<ReturnType<KnowledgeClient["list"]>>>("GET", withQuery("/api/knowledge", params));
    },
    async search(...[query, filter]: Parameters<KnowledgeClient["search"]>): Promise<Awaited<ReturnType<KnowledgeClient["search"]>>> {
      const params = new URLSearchParams();
      appendQueryValue(params, "q", query);
      appendQueryObject(params, filter);
      const decoded = await transport.requestStrict<unknown>("GET", withQuery("/api/knowledge/search", params));
      return parseKnowledgeSearchResponse(decoded);
    },
    async add(...[options]: Parameters<KnowledgeClient["add"]>): Promise<Awaited<ReturnType<KnowledgeClient["add"]>>> {
      const params = new URLSearchParams();
      appendQueryValue(params, "scopeId", options?.scopeId);
      return transport.requestStrict<Awaited<ReturnType<KnowledgeClient["add"]>>>("POST", withQuery("/api/knowledge", params), { ...(omitBodyKeys(options, ["scopeId"]) ?? {}) });
    },
    async reindex(...[scope]: Parameters<KnowledgeClient["reindex"]>): Promise<Awaited<ReturnType<KnowledgeClient["reindex"]>>> {
      const params = new URLSearchParams();
      appendQueryValue(params, "scopeId", scope?.scopeId);
      return transport.requestStrict<Awaited<ReturnType<KnowledgeClient["reindex"]>>>("POST", withQuery("/api/knowledge/reindex", params));
    },
    ...exceptions,
  };
}

export type HistoryDaemonClientExceptions = Pick<
  HistoryClient,
  "show" | "delete"
>;

export function createHistoryDaemonClient(
  transport: DaemonTransport,
  exceptions: HistoryDaemonClientExceptions,
): HistoryClient {
  return {
    async list(...[filter]: Parameters<HistoryClient["list"]>): Promise<Awaited<ReturnType<HistoryClient["list"]>>> {
      const params = new URLSearchParams();
      appendQueryObject(params, filter);
      return transport.requestStrict<Awaited<ReturnType<HistoryClient["list"]>>>("GET", withQuery("/history", params));
    },
    async listDiscoveredScopeRecords(...[filter]: Parameters<HistoryClient["listDiscoveredScopeRecords"]>): Promise<Awaited<ReturnType<HistoryClient["listDiscoveredScopeRecords"]>>> {
      const params = new URLSearchParams();
      appendQueryObject(params, filter);
      return transport.requestStrict<Awaited<ReturnType<HistoryClient["listDiscoveredScopeRecords"]>>>("GET", withQuery("/history/discovered-scope-records", params));
    },
    async search(...[query, filter]: Parameters<HistoryClient["search"]>): Promise<Awaited<ReturnType<HistoryClient["search"]>>> {
      const params = new URLSearchParams();
      appendQueryValue(params, "q", query);
      appendQueryObject(params, filter);
      const decoded = await transport.requestStrict<unknown>("GET", withQuery("/api/history/search", params));
      return parseHistorySearchResponse(decoded);
    },
    async reindex(...[scope]: Parameters<HistoryClient["reindex"]>): Promise<Awaited<ReturnType<HistoryClient["reindex"]>>> {
      const params = new URLSearchParams();
      appendQueryValue(params, "scopeId", scope?.scopeId);
      return transport.requestStrict<Awaited<ReturnType<HistoryClient["reindex"]>>>("POST", withQuery("/history/reindex", params));
    },
    ...exceptions,
  };
}

export type RepoTasksDaemonClientExceptions = Pick<
  RepoTasksClient,
  "show" | "move" | "updateBody" | "create" | "capture"
>;

export function createRepoTasksDaemonClient(
  transport: DaemonTransport,
  exceptions: RepoTasksDaemonClientExceptions,
): RepoTasksClient {
  return {
    async list(...[states, scopeSelector]: Parameters<RepoTasksClient["list"]>): Promise<Awaited<ReturnType<RepoTasksClient["list"]>>> {
      const params = new URLSearchParams();
      appendQueryValue(params, "state", states);
      appendQueryValue(params, "scopeId", scopeSelector?.scopeId);
      return transport.requestStrict<Awaited<ReturnType<RepoTasksClient["list"]>>>("GET", withQuery("/tasks", params));
    },
    async search(...[query, filter]: Parameters<RepoTasksClient["search"]>): Promise<Awaited<ReturnType<RepoTasksClient["search"]>>> {
      const params = new URLSearchParams();
      appendQueryValue(params, "q", query);
      appendQueryObject(params, filter, {"states":"state"});
      const decoded = await transport.requestStrict<unknown>("GET", withQuery("/tasks/search", params));
      return parseTasksSearchResponse(decoded);
    },
    async reindex(...[scope]: Parameters<RepoTasksClient["reindex"]>): Promise<Awaited<ReturnType<RepoTasksClient["reindex"]>>> {
      const params = new URLSearchParams();
      appendQueryValue(params, "scopeId", scope?.scopeId);
      return transport.requestStrict<Awaited<ReturnType<RepoTasksClient["reindex"]>>>("POST", withQuery("/tasks/reindex", params));
    },
    ...exceptions,
  };
}

export type RoutineDaemonClientHandlers = Pick<
  DaemonClientHandlers,
  | "agents"
  | "skills"
  | "recall"
  | "capture"
  | "retract"
  | "resourceDiscovery"
  | "doctor"
  | "audit"
  | "webhook"
  | "modules"
  | "modulesAdmin"
  | "inboundSignals"
  | "answer"
>;

export function createRoutineDaemonClientHandlers(
  transport: DaemonTransport,
): RoutineDaemonClientHandlers {
  return {
    agents: new RoutineAgentsClient(transport),
    skills: new RoutineSkillsClient(transport),
    recall: new RoutineRecallClient(transport),
    capture: new RoutineCaptureClient(transport),
    retract: new RoutineRetractClient(transport),
    resourceDiscovery: new RoutineResourceDiscoveryClient(transport),
    doctor: new RoutineDoctorClient(transport),
    audit: new RoutineAuditClient(transport),
    webhook: new RoutineWebhookClient(transport),
    modules: new RoutineModulesClient(transport),
    modulesAdmin: new RoutineModulesAdminClient(transport),
    inboundSignals: new RoutineInboundSignalsClient(transport),
    answer: new RoutineAnswerClient(transport),
  };
}
